version: '3.7'

services:
  forms-flow-webapi-db:
    image: postgres:11
    environment:
      POSTGRES_USER: ${WEB_API_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${WEB_API_POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${WEB_API_POSTGRES_DB:-webapi}
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '6432:5432'
    restart: unless-stopped
    volumes:
      - ./postgres/webapi:/var/lib/postgresql/data
    networks:
      - forms-flow-webapi-network

  forms-flow-webapi-analytics-db:
    image: mongo
    restart: always
    hostname: forms-flow-webapi-analytics-db
    ports:
       - '27019:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${WEBAPI_ANALYTICS_USERNAME:-mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${WEBAPI_ANALYTICS_PASSWORD:-changeme}
      MONGO_INITDB_DATABASE: ${WEBAPI_ANALYTICS_DATABASE:-analytics}
    volumes:
      - ./mongo_entrypoint/001_user.js:/docker-entrypoint-initdb.d/001_user.js:ro
      - mdb-data:/data/analytics/db/
      - ./mongodb/data/log/:/var/log/mongodb/
      - ./mongodb/mongod.conf:/etc/mongod.conf
    networks:
      - forms-flow-webapi-network

  forms-flow-webapi:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - forms-flow-webapi-db
      - forms-flow-webapi-analytics-db
    ports:
      - '5000:5000'
    volumes:
      - ./:/app:rw
    environment:
      DATABASE_URL: ${WEB_API_DATABASE_URL:-postgresql://postgres:changeme@forms-flow-webapi-db:5432/webapi}
      BPM_TOKEN_API: ${KEYCLOAK_TOKEN_URL}
      BPM_CLIENT_ID: ${KEYCLOAK_BPM_CLIENTID:-forms-flow-bpm}
      BPM_CLIENT_SECRET: ${KEYCLOAK_BPM_CLIENTSECRET}
      CAMUNDA_API_URI: ${CAMUNDA_API_URI:-http://host.docker.internal:8000/camunda}
      JWT_OIDC_WELL_KNOWN_CONFIG: ${KEYCLOAK_JWT_OIDC_CONFIG}
      JWT_OIDC_ALGORITHMS: 'RS256'
      JWT_OIDC_JWKS_URI: ${KEYCLOAK_JWT_OIDC_JWKS_URI}
      JWT_OIDC_ISSUER: ${KEYCLOAK_JWT_OIDC_ISSUER}
      JWT_OIDC_AUDIENCE: ${KEYCLOAK_WEB_CLIENTID:-forms-flow-web}
      JWT_OIDC_CACHING_ENABLED: 'True'
      JWT_OIDC_JWKS_CACHE_TIMEOUT: 300
      FORMSFLOW_API_URL: ${FORMSFLOW_API_URL:-http://host.docker.internal:5000}
      MONGODB_URI: ${MONGODB_URI:-mongodb://changeme:analytics@forms-flow-webapi-analytics-db:27019/analytics?authSource=the_database&authMechanism=SCRAM-SHA-256}
    stdin_open: true # -i
    tty: true # -t
    networks:
      - forms-flow-webapi-network

networks:
  forms-flow-webapi-network:
    driver: 'bridge'

volumes:
  mdb-data:
