apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: jenkin-config
objects:
- 
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: "jenkin-config"
  data:
    password_qtxn: <cfms-postman-operator userid password>
    password_nonqtxn: <cfms-postman-non-operator userid password>
    client_secret: <keycloak client secret>
    zap_with_url: <zap command including dev url for analysis> 
    namespace: nzpnbz-tools
    url: <url of api>/api/v1/
    authurl: <Keycloak domain>
    clientid: <keycload Client ID>
    realm: <keycloak realm>
- 
  kind: BuildConfig
  apiVersion: v1
  metadata:
    name: formsflow-ai-pipeline
    labels:
      app: formsflow-ai-pipeline
      name: formsflow-ai-pipeline
  spec:
    runPolicy: Parallel
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    output: {}
    resources: {}
    postCommit: {}
    nodeSelector:
  status:
    lastVersion: 0

parameters:
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    value: https://github.com/yichun-aot/forms-flow-ai
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
    value: openshift-sbc