apiVersion: v1
kind: Template
metadata:
  name: forms-flow-webapi
objects:
- 
  apiVersion: v1
  kind: ConfigMap
  data:
    BPM_API_BASE: ''
    BPM_CLIENT_ID: 'forms-flow-bpm'
    BPM_CLIENT_SECRET: ''
    BPM_TOKEN_API: ''
    DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/app'
    JWT_OIDC_ALGORITHMS: RS256
    JWT_OIDC_AUDIENCE: forms-flow-web
    JWT_OIDC_CACHING_ENABLED: "True"
    JWT_OIDC_ISSUER: 'https://iam.aot-technologies.com/auth/realms/forms-flow-ai'
    JWT_OIDC_JWKS_CACHE_TIMEOUT: "300"
    JWT_OIDC_JWKS_URI: 'https://iam.aot-technologies.com/auth/realms/forms-flow-ai/protocol/openid-connect/certs'
    JWT_OIDC_WELL_KNOWN_CONFIG: 'https://iam.aot-technologies.com/auth/realms/forms-flow-ai/.well-known/openid-configuration'
  metadata:
    creationTimestamp: null
    labels:
      app: forms-flow-webapi-env
    name: forms-flow-webapi-env

- 
  apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      app: forms-flow-webapi
    name: forms-flow-webapi
  spec:
    replicas: 1
    selector:
      app: forms-flow-webapi
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.network/forms-flow-webapi-network: "true"
          app: forms-flow-webapi
      spec:
        containers:
        - env:
          - name: BPM_API_BASE
            valueFrom:
              configMapKeyRef:
                key: BPM_API_BASE
                name: forms-flow-webapi-env
          - name: BPM_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                key: BPM_CLIENT_ID
                name: forms-flow-webapi-env
          - name: BPM_CLIENT_SECRET
            valueFrom:
              configMapKeyRef:
                key: BPM_CLIENT_SECRET
                name: forms-flow-webapi-env
          - name: BPM_TOKEN_API
            valueFrom:
              configMapKeyRef:
                key: BPM_TOKEN_API
                name: forms-flow-webapi-env
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                key: DATABASE_URL
                name: forms-flow-webapi-env
          - name: JWT_OIDC_ALGORITHMS
            valueFrom:
              configMapKeyRef:
                key: JWT_OIDC_ALGORITHMS
                name: forms-flow-webapi-env
          - name: JWT_OIDC_AUDIENCE
            valueFrom:
              configMapKeyRef:
                key: JWT_OIDC_AUDIENCE
                name: forms-flow-webapi-env
          - name: JWT_OIDC_CACHING_ENABLED
            valueFrom:
              configMapKeyRef:
                key: JWT_OIDC_CACHING_ENABLED
                name: forms-flow-webapi-env
          - name: JWT_OIDC_ISSUER
            valueFrom:
              configMapKeyRef:
                key: JWT_OIDC_ISSUER
                name: forms-flow-webapi-env
          - name: JWT_OIDC_JWKS_CACHE_TIMEOUT
            valueFrom:
              configMapKeyRef:
                key: JWT_OIDC_JWKS_CACHE_TIMEOUT
                name: forms-flow-webapi-env
          - name: JWT_OIDC_JWKS_URI
            valueFrom:
              configMapKeyRef:
                key: JWT_OIDC_JWKS_URI
                name: forms-flow-webapi-env
          - name: JWT_OIDC_WELL_KNOWN_CONFIG
            valueFrom:
              configMapKeyRef:
                key: JWT_OIDC_WELL_KNOWN_CONFIG
                name: forms-flow-webapi-env
          image: ' '
          name: forms-flow-webapi
          ports:
          - containerPort: 5000
          resources: {}
          stdin: true
          tty: true
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - forms-flow-webapi
        from:
          kind: ImageStreamTag
          name: forms-flow-webapi:latest
      type: ImageChange
  status: {}

- 
  apiVersion: v1
  kind: Service
  metadata:
    name: forms-flow-webapi
  spec:
    selector:
      app: forms-flow-webapi
    ports:
      - protocol: TCP
        port: 5000
        targetPort: 5000