# Author: Gurumoorthy Mohan
version: "3.7"

services:
  camunda:
    build:
      context: ./forms-flow-bpm/
      dockerfile: Dockerfile
    ports:
      - '8000:8080'
    env_file:
      - forms-flow-bpm/.env
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_URL_REALM=${KEYCLOAK_URL_REALM}
      - KEYCLOAK_CLIENTID=${KEYCLOAK_CLIENTID}
      - KEYCLOAK_CLIENTSECRET=${KEYCLOAK_CLIENTSECRET}
    networks:
      - camunda-network



networks:
  camunda-network:
    driver: "bridge"

volumes:
  mdb-data:
