# Author: Gurumoorthy Mohan
version: "3.7"
services:
  camunda:
    build:
      context: ./forms-flow-bpm/
      dockerfile: Dockerfile
    ports:
      - '8000:8080'
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_URL_REALM=${KEYCLOAK_URL_REALM}
      - KEYCLOAK_CLIENTID=${KEYCLOAK_CLIENTID}
      - KEYCLOAK_CLIENTSECRET=${KEYCLOAK_CLIENTSECRET}
    networks:
      - camunda-network

  react_formio_app:
    container_name: react_formio_app
    build:
      context: ./forms-flow-web/
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    tty: true
    environment:
      - NODE_ENV=development
      - REACT_APP_CLIENT_ID=5e8320431481d01ecad8645a
      - REACT_APP_STAFF_REVIEWER_ID=5e8320431481d0bee4d8645b
      - REACT_APP_STAFF_DESIGNER_ID=5e81f077bc3e94933a25fc13
      - REACT_APP_USER_RESOURCE_FORM_ID=5e81f07abc3e944bff25fc16
      - REACT_APP_API_SERVER_URL=http://207.216.46.125:3001
      - REACT_APP_API_PROJECT_URL=http://207.216.46.125:3001
    
  mongo:
    image: mongo:4.1
    restart: always
    volumes:
      - mdb-data:/data/db
    env_file:
      - forms-flow-io/.env    
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27018:27017"
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s

  formio:
    build:
      context: ./forms-flow-io/
      dockerfile: Dockerfile
    # The app will restart until Mongo is listening
    restart: always
    links:
      - mongo
    ports:
      - "3001:3001"
    # The application wants to download things to the local directory
    # TODO: really wish I could mount this as read-only
    volumes:
      - ./:/app:rw
    environment:
      DEBUG: formio:*
      NODE_CONFIG: '{"mongo": "mongodb://mongo:27017/formio"}'
      ROOT_EMAIL: admin@example.com
      ROOT_PASSWORD: CHANGEME
    stdin_open: true  # -i
    tty: true         # -t

networks:
  camunda-network:
    driver: "bridge"

volumes:
  mdb-data:
