# Author: Gurumoorthy Mohan
version: "3.7"

services:
  camunda:
    build:
      context: ./forms-flow-bpm/
      dockerfile: Dockerfile
    ports:
      - '8000:8080'
    environment:
      - KEYCLOAK_URL=https://iam.aot-technologies.com
      - KEYCLOAK_URL_REALM=forms-flow-ai
      - KEYCLOAK_CLIENTID=forms-flow-bpm
      - KEYCLOAK_CLIENTSECRET=3dd8d977-f9e0-43b8-9b56-72ad8349b3ea
    networks:
      - camunda-network

  mongo:
    image: mongo:4.1
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mdb-data:/data/db

  forms-flow-io:
    build:
      context: ./forms-flow-io/
      dockerfile: Dockerfile
    # The app will restart until Mongo is listening
    restart: always
    links:
      - mongo
    ports:
      - "3001:3001"
    # The application wants to download things to the local directory
    # TODO: really wish I could mount this as read-only
    volumes:
      - ./:/app:rw
    environment:
      DEBUG: formio:*
      NODE_CONFIG: '{"mongo": "mongodb://mongo:27017/formio"}'
      ROOT_EMAIL: admin@example.com
      ROOT_PASSWORD: CHANGEME
    stdin_open: true  # -i
    tty: true         # -t

networks:
  camunda-network:
    driver: "bridge"

volumes:
  mdb-data: