# Author: Gurumoorthy Mohan
version: "3.7"

services:
  forms-flow-bpm:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8000:8080'
    environment:
      - KEYCLOAK_URL=https://iam.aot-technologies.com
      - KEYCLOAK_URL_REALM=forms-flow-ai
      - KEYCLOAK_CLIENTID=forms-flow-bpm
      - KEYCLOAK_CLIENTSECRET=3dd8d977-f9e0-43b8-9b56-72ad8349b3ea
    networks:
      - forms-flow-bpm-network

  mongo:
    image: mongo:4.1
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mdb-data:/data/db

  forms-flow-io:
    build:
      context: ./
      dockerfile: Dockerfile
    # The app will restart until Mongo is listening
    restart: always
    links:
      - mongo
    ports:
      - "3001:3001"
    # The application wants to download things to the local directory
    # TODO: really wish I could mount this as read-only
    volumes:
      - ./:/app:rw
    environment:
      DEBUG: formio:*
      NODE_CONFIG: '{"mongo": "mongodb://mongo:27017/formio"}'
      ROOT_EMAIL: admin@example.com
      ROOT_PASSWORD: CHANGEME
    stdin_open: true  # -i
    tty: true         # -t

  forms-flow-web:
    container_name: forms-flow-ai
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    tty: true
    environment:
      - NODE_ENV=development
      - REACT_APP_CLIENT_ID=5e8de2b47998f98b2a35554c
      - REACT_APP_STAFF_REVIEWER_ID=5e8de2b47998f941c835554d
      - REACT_APP_STAFF_DESIGNER_ID=5e8dc065a616c3864ab3a17b
      - REACT_APP_USER_RESOURCE_FORM_ID=5e8dc068a616c36c24b3a17e
      - REACT_APP_API_SERVER_URL=http://207.216.46.125:3001
      - REACT_APP_API_PROJECT_URL=http://207.216.46.125:3001

networks:
  forms-flow-bpm-network:
    driver: "bridge"

volumes:
  mdb-data: