delete from ACT_GE_SCHEMA_LOG where id_ = '400';

DROP INDEX ACT_IDX_BATCH_ID;
ALTER TABLE ACT_RU_VARIABLE DROP CONSTRAINT ACT_FK_VAR_BATCH;
ALTER TABLE ACT_RU_VARIABLE DROP COLUMN BATCH_ID_;

DROP INDEX ACT_IDX_VARIABLE_TASK_NAME_TYPE;

DROP INDEX ACT_IDX_TASK_METER_LOG_TIME;
DROP TABLE ACT_RU_TASK_METER_LOG;

ALTER TABLE ACT_RU_INCIDENT DROP COLUMN ANNOTATION_;
ALTER TABLE ACT_HI_INCIDENT DROP COLUMN ANNOTATION_;