<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Details Of Requested Information_d_c1ea22</name>
   <tag></tag>
   <elementGuidId>064792a0-f1d4-4e61-bee6-ab2c4aae9417</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='e2fky8r-informationRequestedPleaseDescribeTheRecordsYouAreRequestingBeAsSpecificAsPossibleAsThisWillAssistTheRequestProcessAttachASeparateSheetIfTheSpaceBelowIsNotSufficient']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e2fky8r-informationRequestedPleaseDescribeTheRecordsYouAreRequestingBeAsSpecificAsPossibleAsThisWillAssistTheRequestProcessAttachASeparateSheetIfTheSpaceBelowIsNotSufficient</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e2fky8r-informationRequestedPleaseDescribeTheRecordsYouAreRequestingBeAsSpecificAsPossibleAsThisWillAssistTheRequestProcessAttachASeparateSheetIfTheSpaceBelowIsNotSufficient</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[informationRequestedPleaseDescribeTheRecordsYouAreRequestingBeAsSpecificAsPossibleAsThisWillAssistTheRequestProcessAttachASeparateSheetIfTheSpaceBelowIsNotSufficient]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e2fky8r-informationRequestedPleaseDescribeTheRecordsYouAreRequestingBeAsSpecificAsPossibleAsThisWillAssistTheRequestProcessAttachASeparateSheetIfTheSpaceBelowIsNotSufficient&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='e2fky8r-informationRequestedPleaseDescribeTheRecordsYouAreRequestingBeAsSpecificAsPossibleAsThisWillAssistTheRequestProcessAttachASeparateSheetIfTheSpaceBelowIsNotSufficient']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e2fky8r']/div/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
   </webElementXpaths>
</WebElementEntity>
