"""empty message

Revision ID: 0ef0de5b0864
Revises: 35041184843a
Create Date: 2021-09-01 07:24:14.085338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON


# revision identifiers, used by Alembic.
revision = '0ef0de5b0864'
down_revision = '35041184843a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sentiment_analysis_results', sa.Column('output_response', JSON, nullable=True))
    op.add_column('sentiment_analysis_results', sa.Column('overall_sentiment', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sentiment_analysis_results',sa.Column('output_response', sa.String(length=80), nullable=True))
    op.drop_column('sentiment_analysis_results', 'overall_sentiment')
    # ### end Alembic commands ###
