"""empty message

Revision ID: 35041184843a
Revises: a635e79631b0
Create Date: 2021-08-31 12:15:45.814594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35041184843a'
down_revision = 'a635e79631b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiment_analysis_results', sa.Column('input_text', sa.String(length=1000), nullable=True))
    op.drop_column('sentiment_analysis_results', 'input_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiment_analysis_results', sa.Column('input_request', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('sentiment_analysis_results', 'input_text')
    # ### end Alembic commands ###
