"""empty message

Revision ID: 7f412f7db7cd
Revises: 0ef0de5b0864
Create Date: 2021-09-01 10:56:56.634633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f412f7db7cd'
down_revision = '0ef0de5b0864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('input_text', sa.String(length=1000), nullable=True),
    sa.Column('overall_sentiment', sa.String(length=100), nullable=True),
    sa.Column('output_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sentiment_analysis_results')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_analysis_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('output_response', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True),
    sa.Column('input_text', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('overall_sentiment', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sentiment_analysis_results_pkey')
    )
    op.drop_table('sentiment_results')
    # ### end Alembic commands ###
