"""form-bundling-updates

Revision ID: 0608ee5f8373
Revises: 0e3d052558ed
Create Date: 2023-03-16 16:13:33.879942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0608ee5f8373'
down_revision = '0e3d052558ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_bundling', 'path_name')
    op.drop_column('form_bundling', 'mapper_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_bundling', sa.Column('mapper_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='mapper id of form inside bundle'))
    op.add_column('form_bundling', sa.Column('path_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Path name of form inside bundle'))
    # ### end Alembic commands ###
