"""formlogs

Revision ID: 0651f6dc4df9
Revises: e664a2f70952
Create Date: 2022-11-08 12:32:35.870623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0651f6dc4df9'
down_revision = 'e664a2f70952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.String(length=30), nullable=False),
    sa.Column('logs', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_logs')
    # ### end Alembic commands ###
