"""Added fields to process-table

Revision ID: 069086882f6c
Revises: d4618d0e45ca
Create Date: 2024-09-26 16:53:01.101934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069086882f6c'
down_revision = 'd4618d0e45ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('process_key', sa.String(), nullable=True))
    op.add_column('process', sa.Column('parent_process_key', sa.String(), nullable=True))
    op.add_column('process', sa.Column('is_subflow', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process', 'is_subflow')
    op.drop_column('process', 'parent_process_key')
    op.drop_column('process', 'process_key')
    # ### end Alembic commands ###
