"""cleanup of submission id

Revision ID: 0b8739ab2097
Revises: 79cd9609e994
Create Date: 2020-09-03 16:19:38.703377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8739ab2097'
down_revision = '79cd9609e994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'form_submission_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('form_submission_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
