"""New fields added to application_audit

Revision ID: 0cb5d5bf4c76
Revises: e1ccede6ab26
Create Date: 2023-07-17 10:28:59.362295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb5d5bf4c76'
down_revision = 'e1ccede6ab26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_audit', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('application_audit', sa.Column('is_resubmit', sa.Boolean(), nullable=True))
    op.add_column('application_audit', sa.Column('percentage', sa.Double(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_audit', 'percentage')
    op.drop_column('application_audit', 'is_resubmit')
    op.drop_column('application_audit', 'color')
    # ### end Alembic commands ###
