"""Form bundling

Revision ID: 0e3d052558ed
Revises: 7dcad446d35c
Create Date: 2023-03-07 12:42:40.019434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e3d052558ed'
down_revision = '9caf8ab8606b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_bundling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rules', postgresql.ARRAY(sa.String()), nullable=True, comment='Rules for bundling'),
    sa.Column('path_name', sa.String(length=100), nullable=False, comment='Path name of form inside bundle'),
    sa.Column('mapper_id', sa.Integer(), nullable=False, comment='mapper id of form inside bundle'),
    sa.Column('form_process_mapper_id', sa.Integer(), nullable=False, comment='Mapper id of bundle'),
    sa.Column('form_order', sa.Integer(), nullable=False, comment='Order of forms inside bundle'),
    sa.Column('parent_form_id', sa.String(length=50), nullable=False, comment='parent id of form inside bundle'),
    sa.ForeignKeyConstraint(['form_process_mapper_id'], ['form_process_mapper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_bundling')
    # ### end Alembic commands ###
