"""theme

Revision ID: 0e526ddca7b3
Revises: fdfe787a197c
Create Date: 2024-04-22 01:44:13.085411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e526ddca7b3'
down_revision = 'fdfe787a197c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme_customization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_name', sa.String(length=50), nullable=False),
    sa.Column('logo_type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=20), nullable=False),
    sa.Column('application_title', sa.String(length=50), nullable=False),
    sa.Column('theme', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theme_customization')
    # ### end Alembic commands ###
