"""set process key, name nullable

Revision ID: 1000f82c87cd
Revises: 656278177438
Create Date: 2021-05-20 19:29:37.752725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1000f82c87cd'
down_revision = '656278177438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_process_mapper', 'process_key',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('form_process_mapper', 'process_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('form_process_mapper', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_process_mapper', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('form_process_mapper', 'process_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('form_process_mapper', 'process_key',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
