"""Added value APPLICATION to authtype enum

Revision ID: 1b4fa1bb6449
Revises: 0cb5d5bf4c76
Create Date: 2023-08-04 13:26:55.687707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4fa1bb6449'
down_revision = '0cb5d5bf4c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE authtype ADD VALUE IF NOT EXISTS 'APPLICATION'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
