"""Added form description

Revision ID: 537aa072d731
Revises: 1b4fa1bb6449
Create Date: 2023-11-06 15:25:15.629148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '537aa072d731'
down_revision = '1b4fa1bb6449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_process_mapper', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_process_mapper', 'description')
    # ### end Alembic commands ###
