"""submitted_by_application_history

Revision ID: 568035a2d276
Revises: 82a8cd6c7aa6
Create Date: 2022-03-08 10:58:09.941799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568035a2d276'
down_revision = '82a8cd6c7aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_audit', sa.Column('submitted_by', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_audit', 'submitted_by')
    # ### end Alembic commands ###
