"""request_types

Revision ID: 5877bd067393
Revises: 0608ee5f8373
Create Date: 2023-03-23 10:44:29.132160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5877bd067393'
down_revision = '0608ee5f8373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_audit', sa.Column('request_type', sa.String(), nullable=True))
    op.add_column('application_audit', sa.Column('request_status', sa.String(), nullable=True))
    op.add_column('application_audit', sa.Column('is_request', sa.Boolean(), nullable=True))
    op.alter_column('application_audit', 'application_status',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_check_constraint(
        'one_of_application_status_or_request_status_is_required',
        'application_audit',
        "(application_status IS NULL AND request_status IS NOT NULL) OR (application_status IS NOT NULL AND request_status IS NULL)"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_audit', 'application_status',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('application_audit', 'is_request')
    op.drop_column('application_audit', 'request_status')
    op.drop_column('application_audit', 'request_type')
    op.drop_constraint('one_of_application_status_or_request_status_is_required', 'application_audit', type_='check')

    # ### end Alembic commands ###
