"""Added submission id to application table

Revision ID: 5fd7397e2751
Revises: 6dd998fc6fed
Create Date: 2022-07-12 13:50:25.638594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd7397e2751'
down_revision = '6dd998fc6fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('submission_id', sa.String(length=100), nullable=True))
    op.execute("update application set submission_id = substring(application.form_url, position('/submission/' in application.form_url)+12) where application.submission_id is null")
    op.alter_column('application', 'submission_id', nullable=False)
    #TODO: Drop column formUrl after downgrade script is in place
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'submission_id')
    # ### end Alembic commands ###
