"""application_status_length_revision

Revision ID: 656278177438
Revises: 0b8739ab2097
Create Date: 2021-04-22 03:43:43.563889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656278177438'
down_revision = '0b8739ab2097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'application_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('application_audit', 'application_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_audit', 'application_status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('application', 'application_status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
