"""This migration script is primarily used to set roles to empty when the users field is empty in attribute filters(field filters). 
This prevents the need to update attribute filters every time a task filter is modified, except in the case of private attribute filters.


Revision ID: 6a8f1ed6ea46
Revises: a22166c687b3
Create Date: 2025-07-22 17:24:38.034895

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '6a8f1ed6ea46'
down_revision = 'a22166c687b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE filter
        SET roles = '{}'
        WHERE filter_type = 'ATTRIBUTE' 
        AND (users = '{}' OR users IS NULL)
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
