"""title length changed

Revision ID: 6fc8e5beebe4
Revises: 2dbcca4a4c28
Create Date: 2024-12-03 15:06:02.156816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc8e5beebe4'
down_revision = '2dbcca4a4c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_process_mapper', 'process_key',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True,
               existing_server_default=sa.text("'Defaultflow'::character varying"))
    op.alter_column('form_process_mapper', 'process_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True,
               existing_server_default=sa.text("'Default Flow'::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_process_mapper', 'process_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'Default Flow'::character varying"))
    op.alter_column('form_process_mapper', 'process_key',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'Defaultflow'::character varying"))
    # ### end Alembic commands ###
