"""Users table

Revision ID: 77d8b68e6c1f
Revises: f1599a5bd658
Create Date: 2024-05-30 16:01:37.273907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77d8b68e6c1f'
down_revision = 'f1599a5bd658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('default_filter', sa.Integer(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True, comment='language code'),
    sa.Column('tenant', sa.String(), nullable=True, comment='tenant key'),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['default_filter'], ['filter.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name', 'tenant', name='uq_tenant_user_name')
    )
    op.alter_column('themes', 'logo_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('themes', 'logo_data',
               existing_type=sa.VARCHAR(),
               comment='logo_data contain a base64 or a URL.',
               existing_nullable=False)
    op.alter_column('themes', 'theme',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Json data',
               existing_nullable=False)
    op.create_unique_constraint('uq_tenant', 'themes', ['tenant'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant', 'themes', type_='unique')
    op.alter_column('themes', 'theme',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Json data',
               existing_nullable=False)
    op.alter_column('themes', 'logo_data',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='logo_data contain a base64 or a URL.',
               existing_nullable=False)
    op.alter_column('themes', 'logo_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_table('user')
    # ### end Alembic commands ###
