"""Filter_order_added

Revision ID: 794497fcac83
Revises: 77d8b68e6c1f
Create Date: 2024-06-20 11:35:43.762882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794497fcac83'
down_revision = '77d8b68e6c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### Added order for display the filter by this order! ###
    op.add_column('filter', sa.Column('order', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filter', 'order')
    # ### end Alembic commands ###
