"""Added value DESIGNER to authtype enum

Revision ID: 7dcad446d35c
Revises: fbe8446ed163
Create Date: 2023-01-30 14:09:56.541509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dcad446d35c'
down_revision = 'fbe8446ed163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE authtype ADD VALUE IF NOT EXISTS 'DESIGNER'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
