"""add process details to application Table

Revision ID: 82a8cd6c7aa6
Revises: e2b6b0b35d87
Create Date: 2022-01-27 01:45:11.062838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "82a8cd6c7aa6"
down_revision = "e2b6b0b35d87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application", sa.Column("process_key", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "application", sa.Column("process_name", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "process_name")
    op.drop_column("application", "process_key")
    # ### end Alembic commands ###
