"""authorization

Revision ID: 8cd292bb049f
Revises: 696557aef580
Create Date: 2022-08-15 10:11:11.662075

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8cd292bb049f'
down_revision = '696557aef580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization',
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.String(), nullable=False),
                    sa.Column('modified_by', sa.String(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False, comment='Authorization ID'),
                    sa.Column('tenant', sa.String(), nullable=True, comment='Tenant key'),
                    sa.Column('auth_type', postgresql.ENUM('DASHBOARD', 'FORM', 'FILTER', name='authtype'),
                              nullable=False, comment='Auth Type'),
                    sa.Column('resource_id', sa.String(), nullable=False, comment='Resource identifier'),
                    sa.Column('resource_details', sa.JSON(), nullable=True, comment='Resource details'),
                    sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=True, comment='Applicable roles'),
                    sa.Column('user_name', sa.String(), nullable=True, comment='Applicable user'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_authorization_auth_type'), 'authorization', ['auth_type'], unique=False)
    op.create_index(op.f('ix_authorization_resource_id'), 'authorization', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authorization_resource_id'), table_name='authorization')
    op.drop_index(op.f('ix_authorization_auth_type'), table_name='authorization')
    op.drop_table('authorization')
    # ### end Alembic commands ###
