"""subflow table

Revision ID: 8feb43e1e408
Revises: 069086882f6c
Create Date: 2024-10-08 13:22:27.369462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8feb43e1e408'
down_revision = '069086882f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('status_changed', sa.Boolean(), nullable=True))
    op.drop_index('ix_process_process_type', table_name='process')
    op.drop_constraint('process_form_process_mapper_id_fkey', 'process', type_='foreignkey')
    op.drop_column('process', 'form_process_mapper_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('form_process_mapper_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('process_form_process_mapper_id_fkey', 'process', 'form_process_mapper', ['form_process_mapper_id'], ['id'])
    op.create_index('ix_process_process_type', 'process', ['process_type'], unique=False)
    op.drop_column('process', 'status_changed')
    # ### end Alembic commands ###
