"""Added default filter

Revision ID: 91f9cd061108
Revises: e8459a47ec29
Create Date: 2023-11-13 12:21:47.163682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f9cd061108'
down_revision = 'e8459a47ec29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    filter_entry = conn.execute(sa.text("SELECT * FROM Filter")).fetchone()

    if not filter_entry:
        # Creating a new filter entry
        insert_stmt = """
            INSERT INTO public.Filter(name, variables, status, created_by, created, criteria, users, roles, task_visible_attributes) 
            VALUES (
                'All Tasks',
                ARRAY['{"name": "applicationId", "label": "Application Id"}'::json, '{"name": "formName", "label": "Form Name"}'::json],
                'active','system',now(),'{}'::json,'{}','{}',
                '{"applicationId": true, "dueDate": true, "priority": true, "assignee": true, "taskTitle": true, "createdDate": true, "groups": true, "followupDate": true}'::json
            )
        """
        conn.execute(sa.text(insert_stmt))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
