"""Add filter type and parent filter id to filter table
   Update existing filter to type TASK

Revision ID: 92bf83135905
Revises: 524194732683
Create Date: 2025-02-21 14:44:55.823150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92bf83135905'
down_revision = '524194732683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type
    enum_type = postgresql.ENUM('TASK', 'ATTRIBUTE', name='FilterType')    
    enum_type.create(op.get_bind(), checkfirst=True)
    op.add_column('filter', sa.Column('filter_type', enum_type, nullable=True, server_default='TASK'))
     # Update existing rows to set the default filter type as task
    op.execute("UPDATE filter SET filter_type = 'TASK' WHERE filter_type IS NULL")
    # Alter the column to set `nullable=False`
    op.alter_column('filter', 'filter_type', nullable=False)
    op.create_index(op.f('ix_filter_filter_type'), 'filter', ['filter_type'], unique=False)
    op.add_column('filter', sa.Column('parent_filter_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_filter_parent_filter_id'), 'filter', ['parent_filter_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filter_parent_filter_id'), table_name='filter')
    op.drop_index(op.f('ix_filter_filter_type'), table_name='filter')
    op.drop_column('filter', 'filter_type')
    op.execute("DROP TYPE \"FilterType\"")
    op.drop_column('filter', 'parent_filter_id')
    # ### end Alembic commands ###
