"""Workflow Migration changes

Revision ID: 960477800395
Revises: 8feb43e1e408
Create Date: 2024-10-29 11:24:12.569841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '960477800395'
down_revision = '8feb43e1e408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_process_mapper', sa.Column('is_migrated', sa.Boolean(), nullable=True, comment="Is workflow migrated", server_default='false'))
    # Update process_name of format process_name(process_key) to process_name 
    # Ex: "Two Step Approval (two-step-approval)" to "Two Step Approval"
    update_query = text("""UPDATE public.form_process_mapper
        SET process_name = regexp_replace(process_name, '\\s*\\([a-zA-Z0-9_-]+\\)$', '')
        WHERE process_name ~ '\\([a-zA-Z0-9_-]+\\)$';""")
    # Execute the SQL statement
    op.execute(update_query)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_process_mapper', 'is_migrated')
    # ### end Alembic commands ###
