"""add_default_filter_analyze_submissions

Revision ID: a22166c687b3
Revises: 98f26d64d7b1
Create Date: 2025-07-11 14:12:18.302655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22166c687b3'
down_revision = '98f26d64d7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('default_submissions_filter', sa.Integer(), nullable=True))
    op.create_foreign_key("user_default_submissions_filter_fkey", 'user', 'submissions_filter', ['default_submissions_filter'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_default_submissions_filter_fkey", 'user', type_='foreignkey')
    op.drop_column('user', 'default_submissions_filter')
    # ### end Alembic commands ###
