"""filter-preference-table-created

Revision ID: a5d9bbf7b5ac
Revises: 92bf83135905
Create Date: 2025-03-25 23:06:11.859670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d9bbf7b5ac'
down_revision = '92bf83135905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_preferences',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for the User Preference entry.'),
    sa.Column('tenant', sa.String(), nullable=True, comment='Tenant identifier (optional, for multi-tenant support).'),
    sa.Column('user_id', sa.String(), nullable=False, comment='Unique identifier for the user.'),
    sa.Column('filter_id', sa.Integer(), nullable=True, comment='Reference to the filter ID.'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='Sort order preference for the applied filter.'),
    sa.Column('hide', sa.Boolean(), nullable=False, comment='Flag to indicate if the filter is hidden.'),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['filter_id'], ['filter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'filter_id', name='_filter_order_uc')
    )
    op.create_index('idx_user_id_and_tenant', 'filter_preferences', ['tenant', 'user_id'], unique=False)
    op.create_index(op.f('ix_filter_preferences_user_id'), 'filter_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filter_preferences_user_id'), table_name='filter_preferences')
    op.drop_index('idx_user_id_and_tenant', table_name='filter_preferences')
    op.drop_table('filter_preferences')
    # ### end Alembic commands ###
