"""Task_outcome_configuration_table

Revision ID: 47d590c1d289
Revises: a5d9bbf7b5ac
Create Date: 2025-05-05 17:50:42.349349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac75256dc5c9'
down_revision = 'a5d9bbf7b5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_outcome_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=False, comment='Task ID'),
    sa.Column('task_outcome', postgresql.ARRAY(sa.JSON()), nullable=True, comment='Task outcome'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='Created by'),
    sa.Column('tenant', sa.String(length=100), nullable=True, comment='Tenant key'),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_outcome_configuration_task_id'), 'task_outcome_configuration', ['task_id'], unique=True)
    op.create_index(op.f('ix_task_outcome_configuration_tenant'), 'task_outcome_configuration', ['tenant'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_outcome_configuration_tenant'), table_name='task_outcome_configuration')
    op.drop_index(op.f('ix_task_outcome_configuration_task_id'), table_name='task_outcome_configuration')
    op.drop_table('task_outcome_configuration')
    # ### end Alembic commands ###
