"""Added major & minor version columns to form history table.

Revision ID: ae48e890f2e2
Revises: b0ecd447cfa5
Create Date: 2024-08-28 11:29:41.480868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae48e890f2e2'
down_revision = 'b0ecd447cfa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_history', sa.Column('major_version', sa.Integer(), nullable=True))
    op.add_column('form_history', sa.Column('minor_version', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_form_history_major_version'), 'form_history', ['major_version'], unique=False)
    op.create_index(op.f('ix_form_history_minor_version'), 'form_history', ['minor_version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_history_minor_version'), table_name='form_history')
    op.drop_index(op.f('ix_form_history_major_version'), table_name='form_history')
    op.drop_column('form_history', 'minor_version')
    op.drop_column('form_history', 'major_version')
    # ### end Alembic commands ###
