"""Added version to process data

Revision ID: b0ecd447cfa5
Revises: e1d88d2efbcb
Create Date: 2024-08-22 12:04:13.443862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b0ecd447cfa5'
down_revision = 'e1d88d2efbcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('major_version', sa.Integer(), nullable=False))
    op.add_column('process', sa.Column('minor_version', sa.Integer(), nullable=False))
    op.alter_column('process', 'process_data',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=False,
               postgresql_using="process_data::bytea")
    op.create_index(op.f('ix_process_major_version'), 'process', ['major_version'], unique=False)
    op.create_index(op.f('ix_process_minor_version'), 'process', ['minor_version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_minor_version'), table_name='process')
    op.drop_index(op.f('ix_process_major_version'), table_name='process')
    op.alter_column('process', 'process_data',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="process_data::bytea")
    op.drop_column('process', 'minor_version')
    op.drop_column('process', 'major_version')
    # ### end Alembic commands ###
