"""fromlogs

Revision ID: bd9b4b1ae18a
Revises: ddd2ec3a72f2
Create Date: 2022-10-25 22:16:42.847967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd9b4b1ae18a'
down_revision = 'ddd2ec3a72f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.String(length=30), nullable=False),
    sa.Column('logs', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_logs')
    # ### end Alembic commands ###
