"""alter-application-column

Revision ID: ce352567e48f
Revises: 
Create Date: 2020-06-15 16:46:59.123742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce352567e48f'
down_revision = 'f84e765253ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'form_submission_id', type_=sa.VARCHAR(length=100))
    op.alter_column('application', 'process_instance_id', type_=sa.VARCHAR(length=100), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
