"""Added prompt_new_version column in form_process_mapper

Revision ID: d4618d0e45ca
Revises: 9929f234cef0
Create Date: 2024-09-12 15:57:52.395411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4618d0e45ca'
down_revision = '9929f234cef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_process_mapper', sa.Column('prompt_new_version', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_process_mapper', 'prompt_new_version')
    # ### end Alembic commands ###
