"""Script to set current forms accessible to all clients and designers.
Existing forms are added to authorization table - DESIGNER, FORM

Revision ID: e1ccede6ab26
Revises: 7dcad446d35c
Create Date: 2023-04-20 12:27:54.081388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1ccede6ab26'
down_revision = '7dcad446d35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    # get the latest row for each form_id group
    forms = conn.execute(sa.text("""SELECT form_id, max(id) as id, tenant FROM form_process_mapper 
                                    WHERE deleted=false GROUP BY form_id, tenant;"""))
    if forms:
        # insert the current forms to authorization table
        insert_stmt = """INSERT INTO public.authorization (created, created_by, tenant, auth_type, resource_id)
          VALUES (:created, :created_by, :tenant, :auth_type, :resource_id);"""
        for row in forms:
            # insert the values into the target table
            conn.execute(sa.text(insert_stmt), {'created': 'now()', 'created_by': 'designer','tenant': row[2], 'auth_type':'DESIGNER','resource_id':row[0]})
            conn.execute(sa.text(insert_stmt), {'created': 'now()', 'created_by': 'designer','tenant': row[2], 'auth_type':'FORM','resource_id':row[0]})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###