"""filter_order

Revision ID: e1d88d2efbcb
Revises: c8e7baa093ba
Create Date: 2024-06-20 13:55:11.434204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d88d2efbcb'
down_revision = 'c8e7baa093ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### Added order for filter to display based on this order! ###
    op.add_column('filter', sa.Column('order', sa.Integer(), nullable=True, comment='Display order'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filter', 'order')
    # ### end Alembic commands ###
