"""filters

Revision ID: e664a2f70952
Revises: ddd2ec3a72f2
Create Date: 2022-10-19 11:30:19.374693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e664a2f70952'
down_revision = 'ddd2ec3a72f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('variables', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=True, comment='Applicable roles'),
    sa.Column('users', postgresql.ARRAY(sa.String()), nullable=True, comment='Applicable users'),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_tenant'), 'filter', ['tenant'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filter_tenant'), table_name='filter')
    op.drop_table('filter')
    # ### end Alembic commands ###
