"""nrs-demo

Revision ID: e692dc3cfbda
Revises: 6dd998fc6fed
Create Date: 2022-06-22 11:52:11.251260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e692dc3cfbda'
down_revision = '6dd998fc6fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nrs_form_data_mapper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('co_ordinates', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('data', sa.String(length=100), nullable=False),
    sa.Column('inspection_time', sa.DateTime(), nullable=False),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nrs_select_data_mapper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nrs_select_data_mapper')
    op.drop_table('nrs_form_data_mapper')
    # ### end Alembic commands ###
