"""Add private_notes column in application_audit table

Revision ID: e85c21a0c08f
Revises: 6a8f1ed6ea46
Create Date: 2025-11-07 14:58:13.898054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85c21a0c08f'
down_revision = '6a8f1ed6ea46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_audit', sa.Column('private_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_audit', 'private_notes')
    # ### end Alembic commands ###
