"""Adding message_key for spiff

Revision ID: e93591c42ddd
Revises: 069086882f6c
Create Date: 2024-10-10 15:13:21.249651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93591c42ddd'
down_revision = '069086882f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('message_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process', 'message_key')
    # ### end Alembic commands ###
