"""Added constaints to process table.

Revision ID: e9ce28b78478
Revises: 960477800395
Create Date: 2024-11-04 12:00:58.046099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ce28b78478'
down_revision = '960477800395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tenant_process_key', 'process', ['process_key', 'tenant'])
    op.create_unique_constraint('uq_tenant_process_name', 'process', ['name', 'tenant'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_process_name', 'process', type_='unique')
    op.drop_constraint('uq_tenant_process_key', 'process', type_='unique')
    # ### end Alembic commands ###
