"""Form logs

Revision ID: ea133a1fa0b7
Revises: e664a2f70952
Create Date: 2022-11-08 11:52:20.970836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea133a1fa0b7'
down_revision = 'e664a2f70952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('variables', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=True, comment='Applicable roles'),
    sa.Column('users', postgresql.ARRAY(sa.String()), nullable=True, comment='Applicable users'),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_tenant'), 'filter', ['tenant'], unique=False)
    op.create_table('form_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.String(length=30), nullable=False),
    sa.Column('logs', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_logs')
    op.drop_index(op.f('ix_filter_tenant'), table_name='filter')
    op.drop_table('filter')
    # ### end Alembic commands ###
