"""Added index for tenant columns and columns in process table

Revision ID: f581ec5971eb
Revises: 6fc8e5beebe4
Create Date: 2025-01-10 09:51:38.407463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f581ec5971eb'
down_revision = '6fc8e5beebe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_authorization_tenant'), 'authorization', ['tenant'], unique=False)
    op.create_index(op.f('ix_form_process_mapper_tenant'), 'form_process_mapper', ['tenant'], unique=False)
    op.create_index('idx_tenant_is_subflow', 'process', ['tenant', 'is_subflow'], unique=False)
    op.create_index('idx_tenant_parent_process_key', 'process', ['tenant', 'parent_process_key'], unique=False)
    op.create_index(op.f('ix_process_name'), 'process', ['name'], unique=False)
    op.create_index(op.f('ix_process_parent_process_key'), 'process', ['parent_process_key'], unique=False)
    op.create_index(op.f('ix_process_tenant'), 'process', ['tenant'], unique=False)
    op.create_index(op.f('ix_themes_tenant'), 'themes', ['tenant'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_themes_tenant'), table_name='themes')
    op.drop_index(op.f('ix_process_tenant'), table_name='process')
    op.drop_index(op.f('ix_process_parent_process_key'), table_name='process')
    op.drop_index(op.f('ix_process_name'), table_name='process')
    op.drop_index('idx_tenant_parent_process_key', table_name='process')
    op.drop_index('idx_tenant_is_subflow', table_name='process')
    op.drop_index(op.f('ix_form_process_mapper_tenant'), table_name='form_process_mapper')
    op.drop_index(op.f('ix_authorization_tenant'), table_name='authorization')
    # ### end Alembic commands ###
