"""create analyze_submissions_filter preferences table

Revision ID: 98f26d64d7b1
Revises: c384c1ce7cd7
Create Date: 2025-07-10 14:02:51.733660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98f26d64d7b1'
down_revision = 'c384c1ce7cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyze_submissions_filter',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for the filter preference entry.'),
    sa.Column('tenant', sa.String(), nullable=True, comment='Tenant identifier (optional, for multi-tenant support).'),
    sa.Column('user', sa.String(), nullable=False, comment='Unique identifier for the user.'),
    sa.Column('parent_form_id', sa.String(length=100), nullable=False, comment='ID of the parent form.'),
    sa.Column('variables', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), nullable=True, comment='Variables associated with the filter.'),
    sa.Column('is_default', sa.Boolean(), nullable=False, server_default='false', comment='Flag to indicate if this is the default filter.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true', comment='Flag to indicate if the filter is active.'),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user', 'parent_form_id', name='_user_parent_form_id_uc')
    )
    op.create_index('idx_user_and_tenant_filter', 'analyze_submissions_filter', ['tenant', 'user'], unique=False)
    op.create_index(op.f('ix_analyze_submissions_filter_parent_form_id'), 'analyze_submissions_filter', ['parent_form_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyze_submissions_filter_parent_form_id'), table_name='analyze_submissions_filter')
    op.drop_index('idx_user_and_tenant_filter', table_name='analyze_submissions_filter')
    op.drop_table('analyze_submissions_filter')
    # ### end Alembic commands ###
