"""Form versioning

Revision ID: fbe8446ed163
Revises: 1a55b7674144
Create Date: 2023-01-23 18:59:45.066568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe8446ed163'
down_revision = '1a55b7674144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_form_history_parent_form_id'), 'form_history', ['parent_form_id'], unique=False)
    op.execute("update form_history set change_log  = jsonb_set(cast(change_log  as jsonb), '{new_version}', 'true') where id in  (select  MIN(id) as MinId from form_history group by parent_form_id)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_history_parent_form_id'), table_name='form_history')
    # ### end Alembic commands ###
