blank_issues_enabled: false
contact_links:
  - name: "Want to involve us in formsflow.ai integration for your organisation?"
    url: https://www.aot-technologies.com/contact-us/
    about: Even though we have open-sourced our solution, and you are free to test-drive or build a solution using our product with no licensing cost from us, it might make sense to involve us in your project because we drastically reduce the time to implement your solution as well as dramatically reducing risk