blank_issues_enabled: false
contact_links:
  - name: "Want to involve us in formsflow.ai integration for your organisation?"
    url: https://www.aot-technologies.com/contact-us/
    about: It might make sense to involve us in your projects because we are leaders in application integration technology and we can help in drastically reducing the time to implement your solution.
