# Allows us to start the stack without touching too much of our local system
#
# note: the application initialization will download/unpack/configure files
#       in the local directory...
#
# ##### Usage:
# *0. Create a broken symlink: `ln -sf "/.npm-packages/node_modules/" node_modules`
# 1. Start the database: `docker-compose up -d mongo`
# 2. Start the application:  `docker-compose run formio`
# [3]. Stop the database: `docker-compose down` (add --volumes to clear data)
# [4]. Remove lingering docker images: `docker-compose down -v --rmi all`
#
# *TODO: Step 0 is for the bcrypt binary compiled on alpine, which is required...
#        but this step feels like an anti-pattern and a better approach should be found

version: '3.7'
services:
  forms-flow-forms-db:
    image: mongo
    restart: always
    hostname: forms-flow-forms-db
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${FORMIO_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${FORMIO_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${FORMIO_MONGO_DATABASE}
    volumes:
      -  ./mongo_entrypoint/001_user.js:/docker-entrypoint-initdb.d/001_user.js:ro
      - mdb-data:/data/db/
      - ./mongodb/data/log/:/var/log/mongodb/
      - ./mongodb/mongod.conf:/etc/mongod.conf
    networks:
      - forms-flow-forms-network

  forms-flow-forms:
    build:
      context: ./
      dockerfile: Dockerfile
    # The app will restart until Mongo is listening
    restart: always
    links:
      - forms-flow-forms-db
    ports:
      - '3001:3001'
    # The application wants to download things to the local directory
    # TODO: really wish I could mount this as read-only
    volumes:
      - ./:/app:rw
    environment:
      DEBUG: formio:*
      NODE_CONFIG: "{\"mongo\":\"mongodb://${FORMIO_MONGO_USERNAME}:${FORMIO_MONGO_PASSWORD}@forms-flow-forms-db:27017/${FORMIO_MONGO_DATABASE}?authMechanism=SCRAM-SHA-1&authSource=admin\"}"
      ROOT_EMAIL: ${FORMIO_ROOT_EMAIL}
      ROOT_PASSWORD: ${FORMIO_ROOT_PASSWORD}
      FORMIO_DOMAIN: ${FORMIO_DEFAULT_PROJECT_URL}
    stdin_open: true # -i
    tty: true # -t
    networks:
      - forms-flow-forms-network

networks:
  forms-flow-forms-network:
    driver: 'bridge'

volumes:
  mdb-data:
