kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: forms-flow-bpm
  annotations:
    description: ""
    tags: forms-flow-bpm,java
    iconClass: icon-java
parameters:
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    value: https://github.com/AOT-Technologies/forms-flow-ai
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
  - name: SOURCE_CONTEXT_DIR
    displayName: Git context directory
    description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
    value: /forms-flow-bpm
objects:
  -  kind: ImageStream
     apiVersion: v1
     metadata:
       name: forms-flow-bpm
       annotations:
         description: "Keeps track of changes in the application image"
       labels:
         app: forms-flow-bpm
  -  kind: BuildConfig
     apiVersion: v1
     metadata:
       name: forms-flow-bpm
     spec:
       failedBuildsHistoryLimit: 2
       nodeSelector: null
       output:
         to:
           kind: ImageStreamTag
           name: 'forms-flow-bpm:latest'
       postCommit: {}
       resources:
         limits:
           cpu: '1'
           memory: 8Gi
         requests:
           cpu: '1'
           memory: 4Gi
       runPolicy: Serial
       source:
         contextDir: ${SOURCE_CONTEXT_DIR}
         git:
           ref: ${SOURCE_REPOSITORY_REF}
           uri: ${SOURCE_REPOSITORY_URL}
         type: Git
       strategy:
         dockerStrategy:
           dockerfilePath: Dockerfile
         type: Docker
       successfulBuildsHistoryLimit: 5
       triggers:
         - type: ConfigChange