apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
    name: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    stringData:
      db_password: "${PATRONI_PASSWORD}"
      db_username: "${PATRONI_USERNAME}"
      keycloak_clientid: "${keycloak_clientid}"
      keycloak_clientsecret: "${keycloak_clientsecret}"
      keycloak_realm: "${keycloak_realm}"
      camunda_formbuilder_pipeline_username: "${CAMUNDA_FORMBUILDER_PIPELINE_USERNAME}"
      formio_root_email: "${FORMIO_ROOT_EMAIL}"
      formio_root_password: "${FORMIO_ROOT_PASSWORD}"
      formio_jwt_secret: "${FORMIO_JWT_SECRET}"
      camunda_formbuilder_pipeline_password: "${CAMUNDA_FORMBUILDER_PIPELINE_PASSWORD}"
      camunda_analytics_jdbc_user: "${CAMUNDA_ANALYTICS_JDBC_USER}"
      camunda_analytics_jdbc_password: "${CAMUNDA_ANALYTICS_JDBC_PASSWORD}"
      BPM_API_URL: "${BPM_API_URL}"
      BPM_CLIENT_ID: '${FFA_BPM_KEYCLOAK_CLIENTID}'
      BPM_CLIENT_SECRET: '${FFA_BPM_KEYCLOAK_CLIENTSECRET}'
      BPM_TOKEN_API: ''
      JWT_OIDC_ALGORITHMS: RS256
      JWT_OIDC_AUDIENCE: forms-flow-web
      JWT_OIDC_CACHING_ENABLED: "True"
      JWT_OIDC_ISSUER: "${KEYCLOAK_URL}/auth/realms/${keycloak_realm}"
      JWT_OIDC_JWKS_CACHE_TIMEOUT: "300"
      JWT_OIDC_JWKS_URI: '${KEYCLOAK_URL}/auth/realms/${keycloak_realm}/protocol/openid-connect/certs'
      JWT_OIDC_WELL_KNOWN_CONFIG: "${KEYCLOAK_URL}/auth/realms/${keycloak_realm}/.well-known/openid-configuration"
      WEB_API_BASE_URL: "${WEB_API_BASE_URL}"
      DEBUG: formio:*
      MONGODB_URI: "${MONGODB_URI}"
      NODE_CONFIG: '{"mongo": "${MONGODB_URI}"}'
      DATABASE_URL: "postgresql://${PATRONI_USERNAME}:${PATRONI_PASSWORD}@${DATABASE_SERVICE_NAME}:${DATABASE_PORT}/${DATABASE_NAME}"


    type: Opaque

parameters:
  - name: NAME
    description: The name for all created objects.
    required: true
    value: forms-flow-ai
  - name: FORMIO_ROOT_EMAIL
    description: FORMIO_ROOT_EMAIL
    required: true
  - name: FORMIO_ROOT_PASSWORD
    description: FORMIO_ROOT_PASSWORD
    required: true
  - name: FORMIO_JWT_SECRET
    description: FORMIO_JWT_SECRET
    required: true
  - name: CAMUNDA_FORMBUILDER_PIPELINE_PASSWORD
    description: CAMUNDA_FORMBUILDER_PIPELINE_PASSWORD
    required: true
  - name: CAMUNDA_ANALYTICS_JDBC_USER
    description: CAMUNDA_ANALYTICS_JDBC_USER
    required: true
  - name: CAMUNDA_ANALYTICS_JDBC_PASSWORD
    description: CAMUNDA_ANALYTICS_JDBC_PASSWORD
    required: true
  - name: PATRONI_USERNAME
    displayName: PATRONI_USERNAME
    description:
      PATRONI_USERNAME
    required: true
  - name: PATRONI_PASSWORD
    displayName: PATRONI_PASSWORD
    description: PATRONI_PASSWORD
    required: true
  - name: keycloak_clientid
    displayName: keycloak_clientid
    description: keycloak_clientid
    required: true
  - name: keycloak_clientsecret
    displayName: keycloak_clientsecret
    description: keycloak_clientsecret
    required: true
  - name: KEYCLOAK_URL
    displayName: KEYCLOAK_URL
    description: KEYCLOAK_URL
    required: true
  - name: keycloak_realm
    displayName: keycloak_realm
    description: keycloak_realm
    required: true
  - name: CAMUNDA_FORMBUILDER_PIPELINE_USERNAME
    description: CAMUNDA_FORMBUILDER_PIPELINE_USERNAME
    required: true
  - name: FFA_BPM_KEYCLOAK_CLIENTSECRET
    description: FFA_BPM_KEYCLOAK_CLIENTSECRET
    required: true
  - name: FFA_BPM_KEYCLOAK_CLIENTID
    description: FFA_BPM_KEYCLOAK_CLIENTID
    required: true
  - name: WEB_API_BASE_URL
    description: WEB_API_BASE_URL
    required: true
  - name: DATABASE_SERVICE_NAME
    description: DATABASE_SERVICE_NAME
    required: true
  - name: DATABASE_PORT
    description: DATABASE_PORT
    required: true
  - name: DATABASE_NAME
    description: DATABASE_NAME
    required: true
  - name: MONGODB_URI
    description: MONGODB_URI
    required: true
  - name: BPM_API_URL
    description: BPM_API_URL
    required: true
