---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Build template for a sentiment analysis job.
    tags: flask
    iconClass: icon-python
  name: "${NAME}-build-template"
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
      app-group: "${APP_GROUP}"
      template: "${NAME}-build"
  spec:
    source:
      type: Git
      git:
        uri: "${GIT_REPO_URL}"
        ref: "${GIT_REF}"
      contextDir: "${SOURCE_CONTEXT_DIR}"
    strategy:
      type: Docker
      dockerStrategy:
        pullSecret:
          name: ${DOCKER_CRED_NAME}
        env:
          - name: FORMIO_SOURCE_REPO_URL
            value: ${FORMIO_SOURCE_REPO_URL}
          - name: FORMIO_SOURCE_REPO_BRANCH
            value: ${FORMIO_SOURCE_REPO_BRANCH}
        dockerfilePath: "${DOCKER_FILE_PATH}"
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:${OUTPUT_IMAGE_TAG}"
    triggers:
    - type: ConfigChange
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the objects defined in this template.  You
    should keep this as default unless your know what your doing.
  required: true
  value: sentiment-analysis
- name: APP_GROUP
  displayName: App Group
  description: The name assigned to all of the deployments in this project.
  required: true
  value: formsflow.ai
- name: GIT_REPO_URL
  displayName: Git Repo URL
  description: The URL to your GIT repo, don't use the this default unless your just
    experimenting.
  required: true
  value: https://github.com/AOT-Technologies/forms-flow-ai.git
- name: GIT_REF
  displayName: Git Reference
  description: The git reference or branch.
  required: true
  value: master
- name: SOURCE_CONTEXT_DIR
  displayName: Source Context Directory
  description: The source context directory.
  required: true
  value: jobs/sentiment-analysis
- name: OUTPUT_IMAGE_TAG
  displayName: Output Image Tag
  description: The tag given to the built image.
  required: true
  value: latest
- name: DOCKER_FILE_PATH
  displayName: Docker File Path
  description: The path to the docker file defining the build.
  required: false
  value: Dockerfile
- name: DOCKER_CRED_NAME
  displayName: Docker cred secret name
  description: Docker cred secret name
  required: true
  value: docker-creds
- name: FORMIO_SOURCE_REPO_URL
  displayName: formsflow source
  description: formsflow source repo
  required: false
  value: https://github.com/AOT-Technologies/forms-flow-ai.git
- name: FORMIO_SOURCE_REPO_BRANCH
  displayName: Repo Branch name
  description: Repo Branch name
  required: false
  value: feature/sentiment-integration
