apiVersion: template.openshift.io/v1
kind: Template
labels:
    app: ${APP_NAME}
metadata:
  name: forms-flow-web
objects:
  -
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${NAME}-keycloak-config
    data:
      keycloak.json: |-
        {
        "realm": "${REALM}",
        "auth-server-url": "${AUTH_SERVER_URL}" ,
        "ssl-required": "external",
        "resource": "forms-flow-web",
        "public-client": true,
        "verify-token-audience": true,
        "use-resource-role-mappings": true,
        "confidential-port": 0
        }

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${NAME}-config
    data:
      config.js: |-
        // runtime-config.js vars
          window["_env_"] =  {
            "NODE_ENV": "production",
            "REACT_APP_API_SERVER_URL": "${REACT_APP_API_SERVER_URL}",
            "REACT_APP_API_PROJECT_URL": "${REACT_APP_API_PROJECT_URL}",
            "REACT_APP_BPM_URL": "${REACT_APP_BPM_URL}",
            "REACT_APP_KEYCLOAK_CLIENT": "forms-flow-web",
            "REACT_APP_WEB_BASE_URL": "${REACT_APP_WEB_BASE_URL}",
            "REACT_APP_WEBSOCKET_ENCRYPT_KEY": "{REACT_APP_WEBSOCKET_ENCRYPT_KEY}",
            "REACT_APP_KEYCLOAK_URL_REALM": "${REALM}",
            "REACT_APP_KEYCLOAK_URL": "${REACT_APP_KEYCLOAK_URL}",
            "REACT_APP_APPLICATION_NAME": "${REACT_APP_APPLICATION_NAME}",
            "REACT_APP_WEB_BASE_CUSTOM_URL": "${REACT_APP_WEB_BASE_CUSTOM_URL}",
            "REACT_APP_USER_ACCESS_PERMISSIONS": "${REACT_APP_USER_ACCESS_PERMISSIONS}",
            "REACT_APP_DRAFT_ENABLED":"${REACT_APP_DRAFT_ENABLED}",
            "REACT_APP_DRAFT_POLLING_RATE":"${REACT_APP_DRAFT_POLLING_RATE}",
            "REACT_APP_EXPORT_PDF_ENABLED":"${REACT_APP_EXPORT_PDF_ENABLED}",
            "REACT_APP_DOCUMENT_SERVICE_URL":"${REACT_APP_DOCUMENT_SERVICE_URL}"
          }

  -
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app: ${APP_NAME}
      name: ${NAME}
    spec:
      replicas: 1
      selector:
        app: ${APP_NAME}
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources:
          requests:
            cpu: "${CPU_REQUEST}"
            memory: "${MEMORY_REQUEST}"
          limits:
            cpu: "${CPU_LIMIT}"
            memory: "${MEMORY_LIMIT}"
        activeDeadlineSeconds: 21600
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: ${APP_NAME}
        spec:
          containers:
            - env:
              image: docker-registry.default.svc:5000/${IMAGE_NAMESPACE}/${NAME}:${TAG_NAME}
              name: ${NAME}
              ports:
                - containerPort: 8080
              resources: {}
              tty: true
              volumeMounts:
                - name: ${NAME}-keycloak-config
                  readOnly: true
                  mountPath: "${KC_MOUNT_PATH}"
                - name: ${NAME}-config
                  readOnly: true
                  mountPath: "${MOUNT_PATH}"
          restartPolicy: Always
          volumes:
            - name: ${NAME}-keycloak-config
              configMap:
                name: ${NAME}-keycloak-config
                defaultMode: 420
            - name: ${NAME}-config
              configMap:
                name: ${NAME}-config
                defaultMode: 420
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              namespace: "${IMAGE_NAMESPACE}"
              name: "${NAME}:${TAG_NAME}"
          type: ImageChange
    status: {}

  -
    apiVersion: v1
    kind: Service
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app: ${APP_NAME}
      name: ${NAME}
    spec:
      ports:
        - name: "8080"
          port: 8080
          targetPort: 8080
      selector:
        app: ${APP_NAME}
    status:
      loadBalancer: {}

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${NAME}
    spec:
      host: ${FFAWEB_URL}
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}
      wildcardPolicy: None

parameters:
  - name: APP_NAME
    displayName: APP_NAME
    description: The name assigned to all of the OpenShift resources associated to the forms-flow-ai
    required: true
    value: forms-flow-ai
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the
      server instance.
    required: true
    value: forms-flow-web
  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description: The namespace of the OpenShift project containing the imagestream for
      the application.
    value: ""
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    required: true
    value: ""
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 100m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 750m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 100Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 2Gi
  - name: KC_MOUNT_PATH
    displayName: Mount config directory.
    description: The path to where the app config directory will get mounted.
    required: true
    value: /usr/share/nginx/html/config/kc
  - name: MOUNT_PATH
    displayName: Mount config directory.
    description: The path to where the app config directory will get mounted.
    required: true
    value: /usr/share/nginx/html/config/
  - name: FFAWEB_URL
    displayName: FFAWEB_URL
    description:
      Route to access Forms Flow AI Web site
    required: true
  - name: REACT_APP_WEB_BASE_URL
    displayName: REACT_APP_WEB_BASE_URL
    description:
      Route to access Forms Flow AI Web site
    required: true
  - name: REACT_APP_BPM_URL
    displayName: REACT_APP_BPM_URL
    description:
      Route to access Forms Flow AI Web site
    required: true
  - name: REACT_APP_API_PROJECT_URL
    displayName: REACT_APP_API_PROJECT_URL
    description:
      Route to access Forms Flow AI Web site
    required: true
  - name: REACT_APP_API_SERVER_URL
    displayName: REACT_APP_API_SERVER_URL
    description:
      Route to access Forms Flow AI Web site
    required: true
  - name: REACT_APP_WEBSOCKET_ENCRYPT_KEY
    displayName: REACT_APP_WEBSOCKET_ENCRYPT_KEY
    description:
    required: true
  - name: AUTH_SERVER_URL
    displayName: AUTH_SERVER_URL
    description: Authentication server Url
    required: true
  - name: REALM
    displayName: REALM
    description: oidc REALM
    required: true
  - name: REACT_APP_KEYCLOAK_URL
    displayName: REACT_APP_KEYCLOAK_URL
    description: keycloak url without auth part in the url
    required: true
  - name: REACT_APP_APPLICATION_NAME
    displayName: REACT_APP_APPLICATION_NAME
    description: the name displayed in the application home page
    required: true
  - name: REACT_APP_USER_ACCESS_PERMISSIONS
    displayName: REACT_APP_USER_ACCESS_PERMISSIONS
    description: JSON formatted permissions to enable / disable few access on user login
    required: true
  - name: REACT_APP_WEB_BASE_CUSTOM_URL
    displayName: REACT_APP_WEB_BASE_CUSTOM_URL
    description: Clients can use this env variable to provide their custom URL
    required: false
  -name: REACT_APP_DRAFT_ENABLED
    displayName: REACT_APP_DRAFT_ENABLED
    description: Wheather or not to use the draft feature
    required: false
  -name: REACT_APP_DRAFT_POLLING_RATE
    displayName: REACT_APP_DRAFT_POLLING_RATE
    description: The interval in milliseconds for autosaving
    required: false
  -name: REACT_APP_EXPORT_PDF_ENABLED
    displayName: REACT_APP_EXPORT_PDF_ENABLED
    description: Wheather or not to show the Export pdf feature
    required: false
  -name: REACT_APP_DOCUMENT_SERVICE_URL
    displayName: REACT_APP_DOCUMENT_SERVICE_URL
    description: Document related services api url
    required: false
