kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: forms-flow-web
  annotations:
    description: ""
    tags: forms-flow-web
parameters:
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    value: https://github.com/AOT-Technologies/forms-flow-ai
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
  - name: SOURCE_CONTEXT_DIR
    displayName: Git context directory
    description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
    value: /forms-flow-web
objects:
-
  apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: forms-flow-web
    labels:
      app: forms-flow-web
  spec:
    resources:
      limits:
        cpu: '1'
        memory: 8Gi
      requests:
        cpu: '1'
        memory: 4Gi
    runPolicy: Serial
    source:
      contextDir: ${SOURCE_CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
    output:
      to:
        kind: ImageStreamTag
        name: 'forms-flow-web:latest'
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: openshift_Dockerfile
    triggers:
      - type: ImageChange
        imageChange: {}
      - type: ConfigChange

-
  apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: forms-flow-web