apiVersion: template.openshift.io/v1
kind: Template
label:
    app: forms-flow-ai
metadata:
  name: forms-flow-webapi
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: { }
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${NAME}
      spec:
        containers:
        - env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                key: MONGODB_URI
                name: ${FORMIO_SECRET}
          - name: BPM_API_BASE
            valueFrom:
              secretKeyRef:
                key: BPM_API_BASE
                name: ${FORMIO_SECRET}
          - name: BPM_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: BPM_CLIENT_ID
                name: ${FORMIO_SECRET}
          - name: BPM_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: BPM_CLIENT_SECRET
                name: ${FORMIO_SECRET}
          - name: BPM_TOKEN_API
            valueFrom:
              secretKeyRef:
                key: BPM_TOKEN_API
                name: ${FORMIO_SECRET}
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: DATABASE_URL
                name: ${FORMIO_SECRET}
          - name: JWT_OIDC_ALGORITHMS
            valueFrom:
              secretKeyRef:
                key: JWT_OIDC_ALGORITHMS
                name: ${FORMIO_SECRET}
          - name: JWT_OIDC_AUDIENCE
            valueFrom:
              secretKeyRef:
                key: JWT_OIDC_AUDIENCE
                name: ${FORMIO_SECRET}
          - name: JWT_OIDC_CACHING_ENABLED
            valueFrom:
              secretKeyRef:
                key: JWT_OIDC_CACHING_ENABLED
                name: ${FORMIO_SECRET}
          - name: JWT_OIDC_ISSUER
            valueFrom:
              secretKeyRef:
                key: JWT_OIDC_ISSUER
                name: ${FORMIO_SECRET}
          - name: JWT_OIDC_JWKS_CACHE_TIMEOUT
            valueFrom:
              secretKeyRef:
                key: JWT_OIDC_JWKS_CACHE_TIMEOUT
                name: ${FORMIO_SECRET}
          - name: JWT_OIDC_JWKS_URI
            valueFrom:
              secretKeyRef:
                key: JWT_OIDC_JWKS_URI
                name: ${FORMIO_SECRET}
          - name: JWT_OIDC_WELL_KNOWN_CONFIG
            valueFrom:
              secretKeyRef:
                key: JWT_OIDC_WELL_KNOWN_CONFIG
                name: ${FORMIO_SECRET}
          - name: WEB_API_BASE_URL
            valueFrom:
              secretKeyRef:
                key: WEB_API_BASE_URL
                name: ${FORMIO_SECRET}
          image: ${IMAGE_NAMESPACE}/${NAME}:${TAG_NAME}
          name: ${NAME}
        ports:
        - containerPort: 5000
        resources: {}
        stdin: true
        tty: true
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_NAMESPACE}"
          name: "${NAME}:${TAG_NAME}"
      type: ImageChange
  status: {}

-
  apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
  spec:
    selector:
      app: ${NAME}
    ports:
      - protocol: TCP
        port: 5000
        targetPort: 5000

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    host: ${WEBAPI_URL}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}
    wildcardPolicy: None

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the
      server instance.
    required: true
    value: forms-flow-api
  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description: The namespace of the OpenShift project containing the imagestream for
      the application.
    value: ""
  - name: FORMIO_SECRET
    description: Secrets are referred from this.
    required: true
    value: forms-flow-ai
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    required: true
    value: ""
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 100m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 750m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 100Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 2Gi
  - name: KEYCLOAK_REALM
    displayName: KEYCLOAK_REALM
    description:
      KEYCLOAK_REALM
    required: true
  - name: KEYCLOAK_URL
    description: The URL used to connnect to the OIDC provider.
    required: true
  - name: WEBAPI_URL
    displayName: WEBAPI_URL
    description:
      Route to access FFA WEB API
    required: true
  - name: PATRONI_USERNAME
    displayName: PATRONI_USERNAME
    description:
      PATRONI_USERNAME
    required: true
  - name: PATRONI_PASSWORD
    displayName: PATRONI_PASSWORD
    description:
      PATRONI_PASSWORD
    required: true
