apiVersion: template.openshift.io/v1
kind: Template
label:
    app: forms-flow-ai
metadata:
  name: forms-flow-webapi
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: { }
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${NAME}
      spec:
        containers:
        - env:
          - name: BPM_API_URL
            valueFrom:
              configMapKeyRef:
                key: BPM_API_URL
                name: ${FORMSFLOW_CONFIG_NAME}-config
          - name: INSIGHTS_API_BASE
            valueFrom:
              secretKeyRef:
                key: INSIGHTS_API_BASE
                name: ${FORMSFLOW_CONFIG_NAME}-config
          - name: INSIGHTS_API_KEY
            valueFrom:
              secretKeyRef:
                key: INSIGHTS_API_KEY
                name: ${FORMSFLOW_CONFIG_NAME}-config
          - name: BPM_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: BPM_CLIENT_ID
                name: ${FORMSFLOW_SECRET}
          - name: BPM_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: BPM_CLIENT_SECRET
                name: ${FORMSFLOW_SECRET}
          - name: BPM_TOKEN_API
            valueFrom:
              configMapKeyRef:
                key: KEYCLOAK_TOKEN_URL
                name: ${FORMSFLOW_CONFIG_NAME}-config
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: DATABASE_URL  
                name: "${WEBAPI_DB_RESOURCE_NAME}-${IMAGE_TAG}-secret"
          - name: JWT_OIDC_ALGORITHMS
            valueFrom:
              configMapKeyRef:
                key: KEYCLOAK_JWT_OIDC_ALGORITHMS
                name: ${FORMSFLOW_CONFIG_NAME}-config
          - name: JWT_OIDC_AUDIENCE
            valueFrom:
              secretKeyRef:
                key: WEB_CLIENTID
                name: ${FORMSFLOW_SECRET}
          - name: JWT_OIDC_CACHING_ENABLED
            valueFrom:
              configMapKeyRef:
                key: KEYCLOAK_JWT_OIDC_CACHING_ENABLED
                name: ${FORMSFLOW_CONFIG_NAME}-config
          - name: JWT_OIDC_ISSUER
            valueFrom:
              configMapKeyRef:
                key: KEYCLOAK_JWT_OIDC_ISSUER
                name: ${FORMSFLOW_CONFIG_NAME}-config
          - name: JWT_OIDC_JWKS_CACHE_TIMEOUT
            valueFrom:
              configMapKeyRef:
                key: KEYCLOAK_JWT_OIDC_JWKS_CACHE_TIMEOUT
                name: ${FORMSFLOW_CONFIG_NAME}-config
          - name: JWT_OIDC_JWKS_URI
            valueFrom:
              configMapKeyRef:
                key: KEYCLOAK_JWT_OIDC_JWKS_URI
                name: ${FORMSFLOW_CONFIG_NAME}-config
          - name: JWT_OIDC_WELL_KNOWN_CONFIG
            valueFrom:
              configMapKeyRef:
                key: KEYCLOAK_JWT_OIDC_CONFIG
                name: ${FORMSFLOW_CONFIG_NAME}-config
          - name: WEB_API_BASE_URL
            valueFrom:
              configMapKeyRef:
                key: WEB_API_BASE_URL
                name: ${FORMSFLOW_CONFIG_NAME}-config
          - name: FORMSFLOW_API_CORS_ORIGINS
            value: '*'      
          image: image-registry.openshift-image-registry.svc:5000/${IMAGE_NAMESPACE}/${NAME}
          name: ${NAME}
        ports:
        - containerPort: 5000
        resources: {}
        stdin: true
        tty: true
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_NAMESPACE}"
          name: "${NAME}:${TAG_NAME}"
      type: ImageChange
  status: {}

-
  apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
  spec:
    selector:
      app: ${NAME}
    ports:
      - protocol: TCP
        port: 5000
        targetPort: 5000

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    host: ${WEB_API_URL}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}
    wildcardPolicy: None

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the
      server instance.
    required: true
    value: forms-flow-webapi
  - name: IMAGE_TAG
    description: The image tag to pull for the deployment.
    required: true  
  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description: The namespace of the OpenShift project containing the imagestream for
      the application.
    value: formsflow-ai
  - name: INSTANCE
    description: The name of this instance of the application
    displayName: Application Instance Name
    required: true  
  - name: FORMSFLOW_CONFIG_NAME
    description: Secrets are referred from this.
    required: true
    value: forms-flow-ai  
  - name: FORMSFLOW_SECRET
    description: Secrets are referred from this.
    required: true
    value: forms-flow-ai
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    required: true
    value: latest
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 100m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 750m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 100Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 2Gi
  - name: KEYCLOAK_REALM
    displayName: KEYCLOAK_REALM
    description:
      KEYCLOAK_REALM
    required: true
  - name: KEYCLOAK_URL
    description: The URL used to connnect to the OIDC provider.
    required: true
  - name: WEB_API_URL
    displayName: WEB_API_URL
    description:
      Web API URL without https prefix.
    required: true
  - name: WEBAPI_DB_RESOURCE_NAME
    description: Name of database resources created for webapi.
    required: true
    value: webapi-postgresql
