version: '3.7'

services:
  forms-flow-webapi-db:
    image: postgres:11
    environment:
      POSTGRES_USER: ${WEB_API_POSTGRES_USER}
      POSTGRES_PASSWORD: ${WEB_API_POSTGRES_PASSWORD}
      POSTGRES_DB: ${WEB_API_POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '6432:5432'
    restart: unless-stopped
    networks:
      - forms-flow-webapi-network

  forms-flow-webapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - forms-flow-webapi-db
    ports:
      - '5000:5000'
    volumes:
      - ./:/app:rw
    environment:
      DATABASE_URL: ${WEB_API_DATABASE_URL}
    stdin_open: true # -i
    tty: true # -t
    networks:
      - forms-flow-webapi-network

networks:
  forms-flow-webapi-network:
    driver: 'bridge'
