export const initialstate = {
  process: {
    processList: [
      {
        id: "sample_id_1",
        key: "Atm",
        description: null,
        name: null,
        version: 1,
        resource: "atm-workflow.bpmn",
        deploymentId: "deployment_id_1",
        diagram: null,
        suspended: false,
        tenantId: null,
        versionTag: null,
        historyTimeToLive: null,
        startableInTasklist: true,
      },
      {
        id: "sample_id_2",
        key: "atm-process",
        description: null,
        name: "ATM Process",
        version: 1,
        resource: "atm-workflow.bpmn",
        deploymentId: "deployment_id_2",
        diagram: null,
        suspended: false,
        tenantId: null,
        versionTag: "1",
        historyTimeToLive: null,
        startableInTasklist: true,
      },
    ],
    deployments: {
      deploymentList: [
        {
          id: "sample_id_3",
          key: "Atm2",
          description: null,
          name: null,
          version: 1,
          resource: "atm-workflow.bpmn",
          deploymentId: "deployment_id_1",
          diagram: null,
          suspended: false,
          tenantId: null,
          versionTag: null,
          historyTimeToLive: null,
          startableInTasklist: true,
        },
        {
          id: "sample_id_4",
          key: "atm-process4",
          description: null,
          name: "ATM Process4",
          version: 1,
          resource: "atm-workflow.bpmn",
          deploymentId: "deployment_id_2",
          diagram: null,
          suspended: false,
          tenantId: null,
          versionTag: "1",
          historyTimeToLive: null,
          startableInTasklist: true,
        },
      ]
    },
    workflowAssociated: {
      label: "Default Flow",
      tenant: null,
      value: "Defaultflow",
    }
  },
};
