"""tenant

Revision ID: 133c7a38c5f3
Revises: 66f6139e309f
Create Date: 2020-06-08 12:59:40.503500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133c7a38c5f3'
down_revision = '66f6139e309f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_name', sa.String(), nullable=False),
    sa.Column('relam', sa.String(), nullable=False),
    sa.Column('audience', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant')
    # ### end Alembic commands ###
