"""initial database migration

Revision ID: 49d95cf7d41a
Revises: 
Create Date: 2020-05-27 11:39:03.060631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d95cf7d41a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FORM_PROCESS_MAPPER',
    sa.Column('mapper_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.String(length=50), nullable=False),
    sa.Column('form_name', sa.String(length=100), nullable=False),
    sa.Column('form_revision_number', sa.String(length=10), nullable=False),
    sa.Column('process_definition_key', sa.String(length=50), nullable=False),
    sa.Column('process_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('comments', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.Column('modified_by', sa.String(length=20), nullable=False),
    sa.Column('modified_on', sa.Date(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('mapper_id')
    )
    op.create_table('FAI_APPLICATION',
    sa.Column('application_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_name', sa.String(length=100), nullable=False),
    sa.Column('application_status', sa.String(length=10), nullable=False),
    sa.Column('mapper_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.Column('modified_by', sa.String(length=20), nullable=False),
    sa.Column('modified_on', sa.Date(), nullable=False),
    sa.Column('submission_id', sa.String(length=30), nullable=False),
    sa.Column('process_instance_id', sa.String(length=30), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mapper_id'], ['FORM_PROCESS_MAPPER.mapper_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('FAI_APPLICATION_AUDIT',
    sa.Column('application_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_name', sa.String(length=100), nullable=False),
    sa.Column('application_status', sa.String(length=10), nullable=False),
    sa.Column('mapper_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.Column('modified_by', sa.String(length=20), nullable=False),
    sa.Column('modified_on', sa.Date(), nullable=False),
    sa.Column('submission_id', sa.String(length=30), nullable=False),
    sa.Column('process_instance_id', sa.String(length=30), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mapper_id'], ['FORM_PROCESS_MAPPER.mapper_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FAI_APPLICATION_AUDIT')
    op.drop_table('FAI_APPLICATION')
    op.drop_table('FORM_PROCESS_MAPPER')
    # ### end Alembic commands ###
