"""add formiotoken table

Revision ID: 66f6139e309f
Revises: 49d95cf7d41a
Create Date: 2020-05-29 11:26:48.440463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f6139e309f'
down_revision = '49d95cf7d41a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FAI_FORMIO_TOKEN',
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keycloak_role', sa.String(length=50), nullable=False),
    sa.Column('formio_token', sa.String(length=500), nullable=False),
    sa.Column('formio_role', sa.String(length=50), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('FAI_APPLICATION_COMMUNICATION',
    sa.Column('communication_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=3000), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['FAI_APPLICATION.application_id'], ),
    sa.PrimaryKeyConstraint('communication_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FAI_APPLICATION_COMMUNICATION')
    op.drop_table('FAI_FORMIO_TOKEN')
    # ### end Alembic commands ###
