version: "3.7"
networks:
  forms-flow-network:
    driver: bridge
x-keycloak-db-service: &keycloak-db
  image: postgres:latest

services:
  keycloak_db:
    <<: *keycloak-db
    container_name: keycloak_db
    restart: always
    volumes:
      - ../../forms-flow-idm/keycloak/postgres/keyclaok:/data/postgres
    environment:
      POSTGRES_DB: ${KEYCLOAK_JDBC_DB:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_JDBC_USER:-admin}
      POSTGRES_PASSWORD: ${KEYCLOAK_JDBC_PASSWORD:-changeme}
    ports:
      - "5431:5431"
    networks:
      - forms-flow-network
  forms-flow-forms-db:
    image: mongo:5.0
    restart: always
    container_name: forms-flow-forms-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${FORMIO_DB_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${FORMIO_DB_PASSWORD:-changeme}
      MONGO_INITDB_DATABASE: ${FORMIO_DB_NAME:-formio}
    volumes:
      - ../../formsflow-forms/mongo_entrypoint/001_user.js:/docker-entrypoint-initdb.d/001_user.js:ro
      - ../../formsflow-forms/mongodb/data/db/:/data/db/
      - ../../formsflow-forms/mongodb/data/log/:/var/log/mongodb/
      - ../../formsflow-forms/mongodb/mongod.conf:/etc/mongod.conf
    ports:
      - "27018:27017"
    networks:
      - forms-flow-network
  forms-flow-bpm-db:
    <<: *keycloak-db
    restart: always
    container_name: forms-flow-bpm-db
    environment:
      POSTGRES_USER: ${CAMUNDA_JDBC_USER:-admin}
      POSTGRES_PASSWORD: ${CAMUNDA_JDBC_PASSWORD:-changeme}
      POSTGRES_DB: ${CAMUNDA_JDBC_DB_NAME:-formsflow-bpm}
    volumes:
      - ../../forms-flow-bpm/postgres/camunda:/var/lib/postgresql/data 777
    ports:
      - "5432:5432"
    networks:
      - forms-flow-network
  forms-flow-webapi-db:
    <<: *keycloak-db
    restart: always
    container_name: forms-flow-webapi-db
    environment:
      POSTGRES_USER: ${FORMSFLOW_API_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${FORMSFLOW_API_DB_PASSWORD:-changeme}
      POSTGRES_DB: ${FORMSFLOW_API_DB_NAME:-webapi}
    volumes:
      - ../../forms-flow-api/postgres/webapi:/var/lib/postgresql/data 777
    ports:
      - "6432:5432"
    networks:
      - forms-flow-network
  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    container_name: keycloak
    restart: always
    volumes:
      - ../../forms-flow-idm/keycloak/imports:/opt/jboss/keycloak/imports
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/formsflow-ai-realm.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak_db
      - DB_DATABASE=${KEYCLOAK_JDBC_DB:-keycloak}
      - DB_USER=${KEYCLOAK_JDBC_USER-admin}
      - DB_PASSWORD=${KEYCLOAK_JDBC_PASSWORD:-changeme}
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USER:-admin}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-changeme}
    ports:
      - "8080:8080"    
    depends_on:
      - keycloak_db
      - forms-flow-forms-db
      - forms-flow-bpm-db
      - forms-flow-webapi-db
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080/auth/realms/forms-flow-ai"]
      interval: 30s
      timeout: 10s
      retries: 10 
    networks:
      - forms-flow-network
  
  forms-flow-forms:
    container_name: forms-flow-forms
    image: formsflow/forms-flow-forms:v5.1.0
    # The app will restart until Mongo is listening
    restart: always
    depends_on:
      - keycloak
      - keycloak_db
      - forms-flow-forms-db
      - forms-flow-bpm-db
      - forms-flow-webapi-db
    ports:
      - '3001:3001'
    # The application wants to download things to the local directory
    environment:
      DEBUG: formio:*
      NODE_CONFIG: "{\"mongo\":\"mongodb://${FORMIO_DB_USERNAME:-admin}:${FORMIO_DB_PASSWORD:-changeme}@forms-flow-forms-db:27017/${FORMIO_DB_NAME:-formio}?authSource=admin\"}"
      ROOT_EMAIL: ${FORMIO_ROOT_EMAIL:-admin@example.com}
      ROOT_PASSWORD: ${FORMIO_ROOT_PASSWORD:-changeme}
      FORMIO_DOMAIN: ${FORMIO_DEFAULT_PROJECT_URL}
      FORMIO_JWT_SECRET: ${FORMIO_JWT_SECRET:---- change me now ---}
      FORMIO_JWT_EXPIRE: ${FORMIO_JWT_EXPIRE:-240}
      FORMIO_CLIENT_UI: ${FORMIO_CLIENT_UI:-false}
      MULTI_TENANCY_ENABLED: ${MULTI_TENANCY_ENABLED:-false}
    stdin_open: true # -i
    tty: true # -t
    networks:
      - forms-flow-network

  forms-flow-bpm:
    build:
      context: ../../forms-flow-bpm/
      dockerfile: Dockerfile
    container_name: forms-flow-bpm
    restart: always
    depends_on:
      - keycloak
      - forms-flow-forms
      - keycloak_db
      - forms-flow-forms-db
      - forms-flow-bpm-db
      - forms-flow-webapi-db
    ports:
      - '8000:8080'
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_URL_REALM=${KEYCLOAK_URL_REALM:-forms-flow-ai}
      - KEYCLOAK_CLIENTID=${KEYCLOAK_BPM_CLIENT_ID:-forms-flow-bpm}
      - KEYCLOAK_CLIENTSECRET=${KEYCLOAK_BPM_CLIENT_SECRET:-e4bdbd25-1467-4f7f-b993-bc4b1944c943}
      - CAMUNDA_JDBC_URL=${CAMUNDA_JDBC_URL:-jdbc:postgresql://forms-flow-bpm-db:5432/formsflow-bpm}
      - CAMUNDA_JDBC_USER=${CAMUNDA_JDBC_USER:-admin}
      - CAMUNDA_JDBC_PASSWORD=${CAMUNDA_JDBC_PASSWORD:-changeme}
      - CAMUNDA_JDBC_DRIVER=${CAMUNDA_JDBC_DRIVER:-org.postgresql.Driver}
#      - CAMUNDA_HIKARI_CONN_TIMEOUT=${CAMUNDA_HIKARI_CONN_TIMEOUT}
#      - CAMUNDA_HIKARI_IDLE_TIMEOUT=${CAMUNDA_HIKARI_IDLE_TIMEOUT}
#      - CAMUNDA_HIKARI_MAX_POOLSIZE=${CAMUNDA_HIKARI_MAX_POOLSIZE}
#      - CAMUNDA_HIKARI_VALID_TIMEOUT=${CAMUNDA_HIKARI_VALID_TIMEOUT}
#      - CAMUNDA_BPM_HISTORY_LEVEL=${CAMUNDA_BPM_HISTORY_LEVEL}
#      - CAMUNDA_AUTHORIZATION_FLAG=${CAMUNDA_AUTHORIZATION_FLAG}
#      - CAMUNDA_AUTHORIZATION_REVOKE_CHECK_FLAG=${CAMUNDA_AUTHORIZATION_REVOKE_CHECK_FLAG}
#      - CAMUNDA_JOB_CORE_POOL_SIZE=${CAMUNDA_JOB_CORE_POOL_SIZE}
#      - CAMUNDA_JOB_LOCK_TIME_MILLIS=${CAMUNDA_JOB_LOCK_TIME_MILLIS}
#      - CAMUNDA_JOB_MAXJOBS_PER_ACQUISITION=${CAMUNDA_JOB_MAXJOBS_PER_ACQUISITION}
#      - CAMUNDA_JOB_MAX_POOL_SIZE=${CAMUNDA_JOB_MAX_POOL_SIZE}
#      - CAMUNDA_JOB_QUEUE_SIZE=${CAMUNDA_JOB_QUEUE_SIZE}
#      - CAMUNDA_JOB_WAIT_TIME_MILLIS=${CAMUNDA_JOB_WAIT_TIME_MILLIS}
#      - CAMUNDA_JOB_MAX_WAIT=${CAMUNDA_JOB_MAX_WAIT}
#      - CAMUNDA_METRICS_FLAG=${CAMUNDA_METRICS_FLAG}
      - CAMUNDA_APP_ROOT_LOG_FLAG=${CAMUNDA_APP_ROOT_LOG_FLAG:-error}
      - FORMSFLOW_API_URL=http://forms-flow-webapi:5000
      - FORMIO_URL=${FORMIO_DEFAULT_PROJECT_URL}
      - FORMIO_ROOT_EMAIL=${FORMIO_ROOT_EMAIL:-admin@example.com}
      - FORMIO_ROOT_PASSWORD=${FORMIO_ROOT_PASSWORD:-changeme}
      - APP_SECURITY_ORIGIN=${APP_SECURITY_ORIGIN:-*}
      - WEBSOCKET_SECURITY_ORIGIN=${WEBSOCKET_SECURITY_ORIGIN}
      - WEBSOCKET_MESSAGE_TYPE=${WEBSOCKET_MESSAGE_TYPE:-TASK_EVENT}
      - WEBSOCKET_ENCRYPT_KEY=${WEBSOCKET_ENCRYPT_KEY:-giert989jkwrgb@DR55}
      - DATA_BUFFER_SIZE=${DATA_BUFFER_SIZE:-2}
      - IDENTITY_PROVIDER_MAX_RESULT_SIZE=${IDENTITY_PROVIDER_MAX_RESULT_SIZE:-250}
      - KEYCLOAK_WEB_CLIENTID=${KEYCLOAK_WEB_CLIENTID:-}
      - KEYCLOAK_ENABLE_CLIENT_AUTH=${KEYCLOAK_ENABLE_CLIENT_AUTH:-false}
      - BPM_CLIENT_CONN_TIMEOUT=${BPM_CLIENT_CONN_TIMEOUT:-5000}
      - DATA_ANALYSIS_URL=${DATA_ANALYSIS_URL}
      - CUSTOM_SUBMISSION_URL=${CUSTOM_SUBMISSION_URL}
      - CUSTOM_SUBMISSION_ENABLED=${CUSTOM_SUBMISSION_ENABLED:-false}
      - MULTI_TENANCY_ENABLED=${MULTI_TENANCY_ENABLED:-false}
      - FORMSFLOW_ADMIN_URL=${FORMSFLOW_ADMIN_URL:-}
      - REDIS_ENABLED=${REDIS_ENABLED:-false}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSCODE=${REDIS_PASSCODE:-changeme}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-false} 
    networks:
      - forms-flow-network
  forms-flow-webapi:
    build:
      context: ../../forms-flow-api/
      dockerfile: Dockerfile
    container_name: forms-flow-webapi
    restart: unless-stopped
    depends_on:
      - keycloak
      - forms-flow-forms
      - forms-flow-bpm
      - keycloak_db
      - forms-flow-forms-db
      - forms-flow-bpm-db
      - forms-flow-webapi-db

    entrypoint: "/wait-for-service.sh forms-flow-webapi-db:5432 -s -- ./entrypoint.sh"
    ports:
      - '5000:5000'
    volumes:
      - ../../forms-flow-api:/app:rw
    environment:
      INSIGHT_API_KEY: ${INSIGHT_API_KEY}
      INSIGHT_API_URL: ${INSIGHT_API_URL}
      DATABASE_URL: ${FORMSFLOW_API_DB_URL:-postgresql://postgres:changeme@forms-flow-webapi-db:5432/webapi}
      BPM_TOKEN_API: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/protocol/openid-connect/token
      BPM_CLIENT_ID: ${KEYCLOAK_BPM_CLIENT_ID:-forms-flow-bpm}
      BPM_CLIENT_SECRET: ${KEYCLOAK_BPM_CLIENT_SECRET:-e4bdbd25-1467-4f7f-b993-bc4b1944c943}
      BPM_API_URL: http://forms-flow-bpm:8080/camunda
      FORMSFLOW_API_CORS_ORIGINS: ${FORMSFLOW_API_CORS_ORIGINS:-*}
      JWT_OIDC_WELL_KNOWN_CONFIG: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/.well-known/openid-configuration
      JWT_OIDC_JWKS_URI: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/protocol/openid-connect/certs
      JWT_OIDC_ISSUER: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}
      JWT_OIDC_AUDIENCE: ${KEYCLOAK_WEB_CLIENT_ID:-forms-flow-web}
      JWT_OIDC_CACHING_ENABLED: 'True'
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_URL_REALM: ${KEYCLOAK_URL_REALM:-forms-flow-ai}
      WEB_API_BASE_URL: http://forms-flow-webapi:5000
      WEB_BASE_URL: ${WEB_BASE_URL:-null}
      FORMIO_URL: ${FORMIO_DEFAULT_PROJECT_URL}
      FORMIO_ROOT_EMAIL: ${FORMIO_ROOT_EMAIL:-admin@example.com}
      FORMIO_ROOT_PASSWORD: ${FORMIO_ROOT_PASSWORD:-changeme}
      FORMIO_JWT_SECRET: ${FORMIO_JWT_SECRET:---- change me now ---}
      MULTI_TENANCY_ENABLED: ${MULTI_TENANCY_ENABLED:-false}
      KEYCLOAK_ENABLE_CLIENT_AUTH: ${KEYCLOAK_ENABLE_CLIENT_AUTH:-false}
      FORM_EMBED_JWT_SECRET: ${FORM_EMBED_JWT_SECRET:-f6a69a42-7f8a-11ed-a1eb-0242ac120002}

    stdin_open: true # -i
    tty: true # -t
    networks:
      - forms-flow-network
  forms-flow-web:
    container_name: forms-flow-web
    build:
      context: ../../forms-flow-web/
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
        - REACT_APP_API_SERVER_URL=${FORMIO_DEFAULT_PROJECT_URL}
        - REACT_APP_API_PROJECT_URL=${FORMIO_DEFAULT_PROJECT_URL}
        - REACT_APP_KEYCLOAK_CLIENT=${KEYCLOAK_WEB_CLIENTID:-forms-flow-web}
        - REACT_APP_WEB_BASE_URL=${FORMSFLOW_API_URL}
        - REACT_APP_BPM_URL=${BPM_API_URL}
        - REACT_APP_WEBSOCKET_ENCRYPT_KEY=${WEBSOCKET_ENCRYPT_KEY:-giert989jkwrgb@DR55}
        - REACT_APP_KEYCLOAK_URL_REALM=${KEYCLOAK_URL_REALM:-forms-flow-ai}
        - REACT_APP_KEYCLOAK_URL=${KEYCLOAK_URL}
        - REACT_APP_APPLICATION_NAME=${APPLICATION_NAME:-formsflow.ai}
        - REACT_APP_USER_ACCESS_PERMISSIONS=${USER_ACCESS_PERMISSIONS}
        - REACT_APP_WEB_BASE_CUSTOM_URL=${WEB_BASE_CUSTOM_URL}
        - REACT_APP_MULTI_TENANCY_ENABLED=${MULTI_TENANCY_ENABLED:-false}
        - REACT_APP_MT_ADMIN_BASE_URL=${MT_ADMIN_BASE_URL}
        - REACT_APP_MT_ADMIN_BASE_URL_VERSION=${MT_ADMIN_BASE_URL_VERSION}
        - REACT_APP_CUSTOM_SUBMISSION_URL=${CUSTOM_SUBMISSION_URL}
        - REACT_APP_CUSTOM_SUBMISSION_ENABLED=${CUSTOM_SUBMISSION_ENABLED:-false}
        - REACT_APP_DRAFT_ENABLED=${DRAFT_ENABLED:-false}
        - REACT_APP_DRAFT_POLLING_RATE=${DRAFT_POLLING_RATE:-15000}
        - REACT_APP_EXPORT_PDF_ENABLED=${EXPORT_PDF_ENABLED:-false}
        - REACT_APP_PUBLIC_WORKFLOW_ENABLED=${PUBLIC_WORKFLOW_ENABLED:-false}
        - REACT_APP_DOCUMENT_SERVICE_URL=${DOCUMENT_SERVICE_URL}
        - REACT_APP_OPENTELEMETRY_SERVICE=${OPENTELEMETRY_SERVICE:-false}
    depends_on:
      - keycloak
      - forms-flow-forms
      - forms-flow-bpm
      - forms-flow-webapi
      - keycloak_db
      - forms-flow-forms-db
      - forms-flow-bpm-db
      - forms-flow-webapi-db
    ports:
      - "3000:8080"
    tty: true
    networks:
      - forms-flow-network