#Author: Kurian Benoy
FROM python:3.13.2-slim-bullseye

# Copy API utils into working directory
COPY forms-flow-api-utils /forms-flow-documents/forms-flow-api-utils

WORKDIR /forms-flow-documents/app

# install curl, gnupg2 and unzip
RUN  apt-get update \
  && apt-get install -y --no-install-recommends \
  gnupg2 curl unzip git \
  && rm -rf /var/lib/apt/lists/*

# Install Chrome WebDriver
RUN CHROMEDRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE` && \
    mkdir -p /opt/chromedriver-$CHROMEDRIVER_VERSION && \
    curl -sS -o /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip && \
    unzip -qq /tmp/chromedriver_linux64.zip -d /opt/chromedriver-$CHROMEDRIVER_VERSION && \
    rm /tmp/chromedriver_linux64.zip && \
    chmod +x /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver && \
    ln -fs /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver /usr/local/bin/chromedriver

# Add Google Chrome repository key
RUN curl -sS -o /tmp/key.gpg https://dl.google.com/linux/linux_signing_key.pub
RUN apt-key add /tmp/key.gpg && rm /tmp/key.gpg

# Add Google Chrome repository for ARM64
RUN echo "deb [arch=arm64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list

# Update package lists
RUN apt-get update

# Install Chromium for ARM64
RUN apt-get install -y chromium

# Clean up
RUN rm -rf /var/lib/apt/lists/*

# set display port to avoid crash
ENV DISPLAY=:99

COPY forms-flow-documents/requirements.txt .
ENV PATH=/venv/bin:$PATH

RUN : \
    && python3 -m venv /venv \
    && pip install --upgrade pip \
    && pip install -r requirements.txt 

COPY forms-flow-documents/ .
RUN pip install -e . && \
    pip uninstall ecdsa -y && \
    apt-get remove -y \
    git unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    forms-flow-api/forms-flow-api-utils/* \
    /forms-flow-api/forms-flow-api-utils/*


EXPOSE 5006
RUN chmod u+x ./entrypoint
ENTRYPOINT ["/bin/sh", "entrypoint"]
