version: '3.7'

services:
  forms-flow-documents-api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '5006:5006'
    volumes:
      - ./:/app:rw
    environment:
      DATABASE_URL: ${FORMSFLOW_API_DB_URL:-postgresql://postgres:changeme@forms-flow-webapi-db:5432/webapi}
      FORMSFLOW_API_CORS_ORIGINS: ${FORMSFLOW_API_CORS_ORIGINS:-*}
      JWT_OIDC_WELL_KNOWN_CONFIG: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/.well-known/openid-configuration
      JWT_OIDC_JWKS_URI: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/protocol/openid-connect/certs
      JWT_OIDC_ISSUER: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}
      JWT_OIDC_AUDIENCE: ${KEYCLOAK_WEB_CLIENT_ID:-forms-flow-web}
      JWT_OIDC_CACHING_ENABLED: 'True'
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_URL_REALM: ${KEYCLOAK_URL_REALM:-forms-flow-ai}
      FORMSFLOW_API_URL: ${FORMSFLOW_API_URL}
      FORMSFLOW_DOC_API_URL: ${FORMSFLOW_DOC_API_URL}
      FORMIO_URL: ${FORMIO_DEFAULT_PROJECT_URL}
      FORMIO_ROOT_EMAIL: ${FORMIO_ROOT_EMAIL:-admin@example.com}
      FORMIO_ROOT_PASSWORD: ${FORMIO_ROOT_PASSWORD:-changeme}
      CHROME_DRIVER_PATH: ${CHROME_DRIVER_PATH}
      CUSTOM_SUBMISSION_URL: ${CUSTOM_SUBMISSION_URL}
      CUSTOM_SUBMISSION_ENABLED: ${CUSTOM_SUBMISSION_ENABLED}
      FORMIO_JWT_SECRET: ${FORMIO_JWT_SECRET:---- change me now ---}
      MULTI_TENANCY_ENABLED: ${MULTI_TENANCY_ENABLED:-false}
      KEYCLOAK_ENABLE_CLIENT_AUTH: ${KEYCLOAK_ENABLE_CLIENT_AUTH:-false}
    stdin_open: true # -i
    tty: true # -t
    networks:
      - forms-flow-webapi-network

networks:
  forms-flow-webapi-network:
    driver: 'bridge'

volumes:
  mdb-data:
