version: '3.7'
x-redash-service: &redash-service
  build:
    context: .
    args:
      skip_frontend_build: 'false'
  volumes:
    - .:/app
x-redash-environment: &redash-environment
  REDASH_LOG_LEVEL: ${REDASH_LOG_LEVEL}
  REDASH_REDIS_URL: ${REDASH_REDIS_URL}
  REDASH_DATABASE_URL: ${REDASH_DATABASE_URL}
  REDASH_RATELIMIT_ENABLED: ${REDASH_RATELIMIT_ENABLED}
services:
  forms-flow-analytics-server:
    <<: *redash-service
    command: dev_server
    depends_on:
      - forms-flow-analytics-db
      - forms-flow-analytics-redis
    ports:
      - '6000:6000'
      - '5678:5678'
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
    networks:
      - forms-flow-analytics-network

  forms-flow-analytics-scheduler:
    <<: *redash-service
    command: dev_scheduler
    depends_on:
      - forms-flow-analytics-server
    environment:
      <<: *redash-environment
    networks:
      - forms-flow-analytics-network

  forms-flow-analytics-worker:
    <<: *redash-service
    command: dev_worker
    depends_on:
      - forms-flow-analytics-server
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
    networks:
      - forms-flow-analytics-network

  forms-flow-analytics-redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - forms-flow-analytics-network

  forms-flow-analytics-db:
    image: postgres
    environment:
      POSTGRES_USER: ${ANALYTICS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ANALYTICS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ANALYTICS_POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '15432:5432'
    restart: unless-stopped
    volumes:
      - ./postgres/analytics:/data/postgres
    networks:
      - forms-flow-analytics-network

networks:
  forms-flow-analytics-network:
    driver: 'bridge'
