---
kind: Template
apiVersion: v1
metadata:
  name: forms-flow-db
  labels:
    app: forms-flow-db
  annotations:
    description: "MongoDB database running as replicate set"
    tags: "mongodb,replication"
parameters:
  - name: MEMORY_REQUEST
    description: Amount of Memory to Request.
    displayName: Memory Request
    required: true
  - name: MEMORY_LIMIT
    description: Amount of Memory to Limit.
    displayName: Memory Limit
    required: true
  - name: CPU_REQUEST
    description: Amount of CPU to Request.
    displayName: Memory Request
    required: true
  - name: CPU_LIMIT
    description: Amount of CPU to Limit.
    displayName: Memory Limit
    required: true
  - name: MONGODB_SERVICE_NAME
    description: Name of the MongoDB Service
    displayName: MongoDB Service Name
    value: "hamongo"
    required: true
  - name: MONGODB_REPLICAS
    description: Number of MongoDB replica pods
    displayName: MongoDB Replicas
    value: "3"
    required: true
  - name: MONGODB_PASSWORD
    displayName: "MongoDB Connection Password"
    description: "Password for the MongoDB connection user."
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true
  - name: MONGODB_ADMIN_PASSWORD
    displayName: "MongoDB Admin Password"
    description: "Password for the database admin user."
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true
  - name: MONGODB_SECRET_NAME
    displayName: MongoDB Secret.
    description: Name of the Secret containing MongoDB Assets
    value: "mongodb-creds"
    required: true
  - name: MONGODB_USER
    displayName: "MongoDB Connection Username"
    description: "Username for MongoDB user that will be used for accessing the database."
    generate: expression
    from: "[a-zA-Z0-9]{5}"
    required: true
  - name: MONGODB_REPLICA_NAME
    displayName: "Replica Set Name"
    description: "The name of the replica set."
    value: "rs0"
    required: true
  - name: MONGODB_KEYFILE_VALUE
    displayName: "Keyfile Content"
    description: "The value of the MongoDB keyfile (https://docs.mongodb.com/manual/core/security-internal-authentication/#internal-auth-keyfile)."
    generate: expression
    from: "[a-zA-Z0-9]{255}"
    required: true
  - name: MONGODB_IMAGE
    displayName: "MongoDB Docker Image"
    description: "A reference to a supported MongoDB Docker image."
    value: registry.redhat.io/rhscl/mongodb-36-rhel7
    required: true
  - name: MONGODB_IMAGE_TAG
    description: Name of the MongoDB tag that should be used
    displayName: MongoDB Tag
    value: "1"
    required: true
  - name: VOLUME_CAPACITY
    displayName: "Volume Capacity for MongoDB"
    description: "Volume space available for data, e.g. 512Mi, 2Gi."
    required: true
  - name: SC_MONGO
    description: The Storage Class for the MongoDB
    displayName: Storage Class for MongoDB
    required: true
  - name: MONGODB_DATABASE
    displayName: "MongoDB Database Name"
    description: "Name of the MongoDB database accessed."
    value: forms-flow-db
    required: true

objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${MONGODB_SECRET_NAME}
      labels:
        app: formio-chat-mongodb
    stringData:
      database: ${MONGODB_DATABASE}
      username: "${MONGODB_USER}"
      password: "${MONGODB_PASSWORD}"
      admin-username: "admin"
      admin-password: "${MONGODB_ADMIN_PASSWORD}"
      mongo-url: "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_SERVICE_NAME}:27017/${MONGODB_DATABASE}?replicaSet=${MONGODB_REPLICA_NAME}"
      mongo-oplog-url: "mongodb://admin:${MONGODB_ADMIN_PASSWORD}@${MONGODB_SERVICE_NAME}:27017/local?authSource=admin&replicaSet=${MONGODB_REPLICA_NAME}"
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${MONGODB_SERVICE_NAME}"
      labels:
        app: forms-flow-db
    spec:
      ports:
        - name: mongodb
          port: 27017
      selector:
        statefulset: "${MONGODB_SERVICE_NAME}"
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${MONGODB_SERVICE_NAME}-internal"
      labels:
        app: forms-flow-db
      annotations:
        service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    spec:
      clusterIP: None
      ports:
        - name: mongodb
          port: 27017
      selector:
        statefulset: "${MONGODB_SERVICE_NAME}"
  - kind: StatefulSet
    apiVersion: apps/v1
    metadata:
      name: "${MONGODB_SERVICE_NAME}"
      labels:
        app: forms-flow-db
    spec:
      selector:
        matchLabels:
          statefulset: ${MONGODB_SERVICE_NAME}
      serviceName: "${MONGODB_SERVICE_NAME}-internal"
      replicas: ${{MONGODB_REPLICAS}}
      template:
        metadata:
          labels:
            app: forms-flow-db
            statefulset: ${MONGODB_SERVICE_NAME}
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: name
                        operator: In
                        values:
                          - ${MONGODB_SERVICE_NAME}
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: mongo-container
              image: "${MONGODB_IMAGE}:${MONGODB_IMAGE_TAG}"
              ports:
                - containerPort: 27017
              args:
                - "run-mongod-replication"
              volumeMounts:
                - name: mongo-data
                  mountPath: "/var/lib/mongodb/data"
              env:
                - name: MONGODB_USER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: "${MONGODB_SECRET_NAME}"
                - name: MONGODB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: "${MONGODB_SECRET_NAME}"
                - name: MONGODB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database
                      name: "${MONGODB_SECRET_NAME}"
                - name: MONGODB_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: admin-password
                      name: "${MONGODB_SECRET_NAME}"
                - name: MONGO_OPLOG_URL
                  valueFrom:
                    secretKeyRef:
                      key: mongo-oplog-url
                      name: "${MONGODB_SECRET_NAME}"
                - name: MONGODB_REPLICA_NAME
                  value: "${MONGODB_REPLICA_NAME}"
                - name: MONGODB_KEYFILE_VALUE
                  value: "${MONGODB_KEYFILE_VALUE}"
                - name: MONGODB_SERVICE_NAME
                  value: "${MONGODB_SERVICE_NAME}-internal"
              resources:
                limits:
                  memory: "${MEMORY_LIMIT}"
                  cpu: "${CPU_LIMIT}"
                requests:
                  memory: "${MEMORY_REQUEST}"
                  cpu: "${CPU_REQUEST}"
              exec:
                command:
                  - /bin/sh
                  - '-i'
                  - '-c'
                  - >-
                    mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p
                    $MONGODB_PASSWORD --eval="quit()"
      volumeClaimTemplates:
        - metadata:
            name: mongo-data
            labels:
              name: "${MONGODB_SERVICE_NAME}"
              app: forms-flow-db
          spec:
            accessModes: [ ReadWriteOnce ]
            storageClassName: "${SC_MONGO}"
            resources:
              requests:
                storage: "${VOLUME_CAPACITY}"