const ACTION_CONSTANTS = {
  SEND_EMAIL_NOTIFICATION:'SEND_EMAIL_NOTIFICATION',
  SEND_ONE_STEP_APPROVAL:'SEND_ONE_STEP_APPROVAL',
  SET_USER_TOKEN:'SET_USER_TOKEN',
  SET_USER_ROLES:'SET_USER_ROLES',
  SET_USER_DETAILS:'SET_USER_DETAILS',
  ERROR:'ERROR',
  IS_LOADING:'IS_LOADING',
}

export default ACTION_CONSTANTS;
