const ACTION_CONSTANTS = {
  SET_USER_AUTHENTICATION:'SET_USER_AUTHENTICATION',
  SET_USER_TOKEN:'SET_USER_TOKEN',
  SET_USER_ROLES:'SET_USER_ROLES',
  SET_USER_DETAILS:'SET_USER_DETAILS',
  SEND_ONE_STEP_APPROVAL:'SEND_ONE_STEP_APPROVAL',
  SEND_EMAIL_NOTIFICATION:'SEND_EMAIL_NOTIFICATION',
  ERROR:'ERROR',
  IS_LOADING:'IS_LOADING',
  FORM_DELETE:'FORM_DELETE',
  FORM_SUBMISSION_DELETE:'FORM_SUBMISSION_DELETE'
}

export default ACTION_CONSTANTS;
