const ACTION_CONSTANTS = {
  SEND_EMAIL_NOTIFICATION:'SEND_EMAIL_NOTIFICATION',
  SEND_ONE_STEP_APPROVAL:'SEND_ONE_STEP_APPROVAL',
  SET_USER_TOKEN:'SET_USER_TOKEN',
  SET_USER_ROLES:'SET_USER_ROLES',
  SET_USER_DETAILS:'SET_USER_DETAILS',
  ERROR:'ERROR',
  IS_LOADING:'IS_LOADING',
  LIST_TASKS: 'LIST_TASKS',
  TASKS_COUNT:'TASKS_COUNT',
  TASK_DETAIL:'TASK_DETAIL',
  FORM_SUBMISSION_DELETE:'FORM_SUBMISSION_DELETE',
  FORM_DELETE:'FORM_DELETE'
}

export default ACTION_CONSTANTS;
