apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: forms-flow-forms-mdb
objects:
- 
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: mdb-data
    name: mdb-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}

- 
  apiVersion: v1
  kind: ConfigMap
  data:
    MONGO_INITDB_DATABASE: 'formio'
    MONGO_INITDB_ROOT_PASSWORD: 
    MONGO_INITDB_ROOT_USERNAME: 
  metadata:
    creationTimestamp: null
    labels:
      app: forms-flow-forms-mdb-env
    name: forms-flow-forms-mdb-env
- 
  apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      app: forms-flow-forms-mdb
    name: forms-flow-forms-mdb
  spec:
    replicas: 1
    selector:
      app: forms-flow-forms-mdb
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.network/forms-flow-forms-network: "true"
          app: forms-flow-forms-mdb
      spec:
        containers:
        - env:
          - name: MONGO_INITDB_DATABASE
            valueFrom:
              configMapKeyRef:
                key: MONGO_INITDB_DATABASE
                name: forms-flow-forms-mdb-env
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: MONGO_INITDB_ROOT_PASSWORD
                name: forms-flow-forms-mdb-env
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                key: MONGO_INITDB_ROOT_USERNAME
                name: forms-flow-forms-mdb-env
          image: ' '
          name: forms-flow-forms-mdb
          ports:
          - containerPort: 27017
          resources: {}
          volumeMounts:
          - mountPath: /data/db/
            name: mdb-data
        hostname: forms-flow-forms-mdb
        restartPolicy: Always
        volumes:
        - name: mdb-data
          persistentVolumeClaim:
            claimName: mdb-data
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - forms-flow-forms-mdb
        from:
          kind: ImageStreamTag
          name: forms-flow-forms-mdb:latest
      type: ImageChange
  status: {}

- 
  apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      app: forms-flow-forms-mdb
    name: forms-flow-forms-mdb
  spec:
    ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
    selector:
      app: forms-flow-forms-mdb
  status:
    loadBalancer: {}

- 
  apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: forms-flow-forms-mdb
  spec:
    tags:
      - annotations: null
        from:
          kind: DockerImage
          name: 'mongo:latest'
        generation: 2
        importPolicy: {}
        name: latest
        referencePolicy:
          type: Source