apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mongodb_replica_set
  annotations:
    description: "MongoDB database running as replicate set"
    iconClass: "icon-nodejs"
    tags: "nodejs,mongodb,replication,instant-app"
labels:
  app: "${APP_GROUP}"    

parameters:
  - name: MEMORY_REQUEST
    description: Amount of Memory to Request.
    displayName: Memory Request
    required: true
    value: 512Mi

  - name: MEMORY_LIMIT
    description: Amount of Memory to Limit.
    displayName: Memory Limit
    required: true
    value: 3Gi

  - name: CPU_REQUEST
    description: Amount of CPU to Request.
    displayName: Memory Request
    required: true
    value: 500m

  - name: CPU_LIMIT
    description: Amount of CPU to Limit.
    displayName: Memory Limit
    required: true
    value: '1'
    
  - name: MONGODB_SERVICE_NAME
    description: Name of the MongoDB Service
    displayName: MongoDB Service Name
    value: "mongodb"
    required: true

  - name: MONGODB_REPLICAS
    description: Number of MongoDB replica pods
    displayName: MongoDB Replicas
    value: "2"
    required: true

  - name: MONGODB_SECRET_NAME
    displayName: MongoDB Secret.
    description: Name of the Secret containing MongoDB Assets
    value: "mongodb"
    required: true
    
  - name: MONGODB_USER
    displayName: "MongoDB Connection Username"
    description: "Username for MongoDB user that will be used for accessing the database."
    generate: expression
    from: "[a-zA-Z0-9]{5}"
    required: true

  - name: MONGODB_PASSWORD
    displayName: "MongoDB Connection Password"
    description: "Password for the MongoDB connection user."
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true

  - name: MONGODB_DATABASE
    displayName: "MongoDB Database Name"
    description: "Name of the MongoDB database accessed."
    value: formiodb
    required: true

  - name: MONGODB_ADMIN_PASSWORD
    displayName: "MongoDB Admin Password"
    description: "Password for the database admin user."
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true

  - name: MONGODB_REPLICA_NAME
    displayName: "Replica Set Name"
    description: "The name of the replica set."
    value: rs0
    required: true

  - name: MONGODB_KEYFILE_VALUE
    displayName: "Keyfile Content"
    description: "The value of the MongoDB keyfile (https://docs.mongodb.com/manual/core/security-internal-authentication/#internal-auth-keyfile)."
    generate: expression
    from: "[a-zA-Z0-9]{255}"
    required: true

  - name: MONGODB_IMAGE
    displayName: "MongoDB Docker Image"
    description: "A reference to a supported MongoDB Docker image."
    value: "docker-registry.default.svc:5000/openshift/mongodb"
    required: true

  - name: MONGODB_IMAGE_TAG
    description: Name of the MongoDB tag that should be used
    displayName: MongoDB Tag
    value: "3.6"
    required: true

  - name: VOLUME_CAPACITY
    displayName: "Volume Capacity for MongoDB"
    description: "Volume space available for data, e.g. 512Mi, 2Gi."
    required: true
    value: 10Gi

  - name: SC_MONGO
    description: The Storage Class for the MongoDB
    displayName: Storage Class for MongoDB
    required: true
    value: netapp-block-standard

  - name: APP_GROUP
    description: The name assigned to all of the deployments in this project.
    displayName: App Group
    required: true
    value: "mongodb"
    

objects:
# Secrets for mongo DB 
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${MONGODB_SECRET_NAME}
      labels:
        name: "${MONGODB_SERVICE_NAME}"
        app: "${APP_GROUP}"
    stringData:
      username: "${MONGODB_USER}"
      password: "${MONGODB_PASSWORD}"
      admin-username: "admin"
      admin-password: "${MONGODB_ADMIN_PASSWORD}"
      database: "${MONGODB_DATABASE}"
      replica-name: "${MONGODB_REPLICA_NAME}"
      mongo-url: "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_SERVICE_NAME}:27017/${MONGODB_DATABASE}?replicaSet=${MONGODB_REPLICA_NAME}"
      NODE_CONFIG: "{\"mongo\":\"mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_SERVICE_NAME}:27017/${MONGODB_DATABASE}?replicaSet=${MONGODB_REPLICA_NAME}\"}"
      mongo-oplog-url: "mongodb://admin:${MONGODB_ADMIN_PASSWORD}@${MONGODB_SERVICE_NAME}:27017/local?authSource=admin&replicaSet=${MONGODB_REPLICA_NAME}"

  # A non-headless service which takes pod readiness into consideration
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${MONGODB_SERVICE_NAME}"
      labels:
        name: "${MONGODB_SERVICE_NAME}"
        app: "${APP_GROUP}"
    spec:
      ports:
        - name: mongodb
          port: 27017
      selector:
        name: "${MONGODB_SERVICE_NAME}"

  # A headless service to create DNS records
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${MONGODB_SERVICE_NAME}-internal"
      labels:
        name: "${MONGODB_SERVICE_NAME}"
        app: "${APP_GROUP}"
      annotations:
        service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    spec:    
      clusterIP: None
      ports:
        - name: mongodb
          port: 27017
      selector:
        name: "${MONGODB_SERVICE_NAME}"

# Mongo DB StatefulSet
  - kind: StatefulSet
    apiVersion: apps/v1beta1
    metadata:
      name: "${MONGODB_SERVICE_NAME}"
      labels:
        app: "${APP_GROUP}"
    spec:
      serviceName: "${MONGODB_SERVICE_NAME}-internal"
      replicas: "${MONGODB_REPLICAS}"
      template:
        metadata:
          labels:
            name: "${MONGODB_SERVICE_NAME}"
            app: "${APP_GROUP}"
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: name
                    operator: In
                    values: 
                    - ${MONGODB_SERVICE_NAME}
                topologyKey: "kubernetes.io/hostname"
          containers:
            - name: mongo-container
              image: "${MONGODB_IMAGE}:${MONGODB_IMAGE_TAG}"
              ports:
                - containerPort: 27017
              args:
                - "run-mongod-replication"
              volumeMounts:
                - name: mongo-data
                  mountPath: "/var/lib/mongodb/data"
              env:
                - name: MONGODB_USER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: "${MONGODB_SECRET_NAME}"
                - name: MONGODB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: "${MONGODB_SECRET_NAME}"
                - name: MONGODB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database
                      name: "${MONGODB_SECRET_NAME}"
                - name: MONGODB_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: admin-password
                      name: "${MONGODB_SECRET_NAME}"
                - name: MONGO_OPLOG_URL
                  valueFrom:
                    secretKeyRef:
                      key: mongo-oplog-url
                      name: "${MONGODB_SECRET_NAME}"
                - name: MONGODB_REPLICA_NAME
                  valueFrom:
                    secretKeyRef:
                      key: replica-name
                      name: "${MONGODB_SECRET_NAME}"
                - name: MONGODB_KEYFILE_VALUE
                  value: "${MONGODB_KEYFILE_VALUE}"
                - name: MONGODB_SERVICE_NAME
                  value: "${MONGODB_SERVICE_NAME}-internal"
              resources:
                limits:
                  memory: "${MEMORY_LIMIT}"
                  cpu: "${CPU_LIMIT}"
                requests:
                  memory: "${MEMORY_REQUEST}"
                  cpu: "${CPU_REQUEST}"
              readinessProbe:
                exec:
                  command:
                    - stat
                    - /tmp/initialized
      volumeClaimTemplates:
        - metadata:
            name: mongo-data
            labels:
              name: "${MONGODB_SERVICE_NAME}"
              app: "${APP_GROUP}"
          spec:
            accessModes: [ ReadWriteOnce ]
            storageClassName: "${SC_MONGO}"
            resources:
              requests:
                storage: "${VOLUME_CAPACITY}"