# Author: Gurumoorthy Mohan
version: '3.7'

services:
  forms-flow-forms-db:
    image: mongo
    restart: always
    hostname: forms-flow-forms-db
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${FORMIO_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${FORMIO_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${FORMIO_MONGO_DATABASE}
    volumes:
      - mdb-data:/data/db/
      - ./mongodb/data/log/:/var/log/mongodb/
      - ./mongodb/mongod.conf:/etc/mongod.conf
    networks:
      - forms-flow-forms-network

  forms-flow-forms:
    build:
      context: ../../../forms-flow-forms/
      dockerfile: Dockerfile
    # The app will restart until Mongo is listening
    restart: always
    links:
      - forms-flow-forms-db
    ports:
      - '3001:3001'
    # The application wants to download things to the local directory
    # TODO: really wish I could mount this as read-only
    volumes:
      - ./:/app:rw
    environment:
      DEBUG: formio:*
      NODE_CONFIG: '{"mongo": "mongodb://forms-flow-forms-db:27017/formio"}'
      ROOT_EMAIL: ${FORMIO_ADMIN_EMAIL}
      ROOT_PASSWORD: ${FORMIO_ADMIN_PASSWORD}
    stdin_open: true # -i
    tty: true # -t
    networks:
      - forms-flow-forms-network

networks:
  forms-flow-forms-network:
    driver: 'bridge'

volumes:
  mdb-data:
