---
apiVersion: v1
kind: Template
labels:
  app: "${APP_NAME}-${INSTANCE}"
  name: "${FORMS_FLOW_SECRET_NAME}"
  role: "${ROLE}"
  template: "${FORMS_FLOW_SECRET_NAME}-${INSTANCE}-template"
metadata:
  annotations:
    description: forms-flow-bpm secret generator.
    tags: "${FORMS_FLOW_SECRET_NAME}-${INSTANCE}"
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: "${FORMS_FLOW_SECRET_NAME}"
    stringData:
      db_password: "${PATRONI_PASSWORD}"
      db_username: "${PATRONI_USERNAME}"
      keycloak_clientid: "${keycloak_clientid}"
      keycloak_clientsecret: "${keycloak_clientsecret}"
      keycloak_realm: "${keycloak_realm}"
    type: Opaque
parameters:
  - name: FORMS_FLOW_SECRET_NAME
    displayName: Name
    description:
      The name assigned to all of the OpenShift resources associated to the
      server instance.
    required: true
  - name: INSTANCE
    description: The name of this instance of the application
    displayName: Application Instance Name
    required: true
    value: dev
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: formio
  - name: ROLE
    displayName: Role
    description:
      The role of this service within the application - used for Network
      Policies
    required: true
    value: db
  - name: PATRONI_USERNAME
    displayName: PATRONI_USERNAME
    description:
      PATRONI_USERNAME
    required: true
  - name: PATRONI_PASSWORD
    displayName: PATRONI_PASSWORD
    description:
      PATRONI_PASSWORD
    required: true
  - name: keycloak_clientid
    displayName: keycloak_clientid
    description:
      keycloak_clientid
    required: true
  - name: keycloak_clientsecret
    displayName: keycloak_clientsecret
    description:
      keycloak_clientsecret
    required: true
  - name: keycloak_realm
    displayName: keycloak_realm
    description:
      keycloak_realm
    required: true

