<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Details Of Requested Information</name>
   <tag></tag>
   <elementGuidId>8680a2a0-07c6-4207-879c-fb7ebf00ab3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e2fky8r-informationRequestedPleaseDescribeTheRecordsYouAreRequestingBeAsSpecificAsPossibleAsThisWillAssistTheRequestProcessAttachASeparateSheetIfTheSpaceBelowIsNotSufficient</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'form-control' and @type = 'text' and @name = 'data[informationRequestedPleaseDescribeTheRecordsYouAreRequestingBeAsSpecificAsPossibleAsThisWillAssistTheRequestProcessAttachASeparateSheetIfTheSpaceBelowIsNotSufficient]']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='e2fky8r-informationRequestedPleaseDescribeTheRecordsYouAreRequestingBeAsSpecificAsPossibleAsThisWillAssistTheRequestProcessAttachASeparateSheetIfTheSpaceBelowIsNotSufficient']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e2fky8r-informationRequestedPleaseDescribeTheRecordsYouAreRequestingBeAsSpecificAsPossibleAsThisWillAssistTheRequestProcessAttachASeparateSheetIfTheSpaceBelowIsNotSufficient</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[informationRequestedPleaseDescribeTheRecordsYouAreRequestingBeAsSpecificAsPossibleAsThisWillAssistTheRequestProcessAttachASeparateSheetIfTheSpaceBelowIsNotSufficient]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e2fky8r-informationRequestedPleaseDescribeTheRecordsYouAreRequestingBeAsSpecificAsPossibleAsThisWillAssistTheRequestProcessAttachASeparateSheetIfTheSpaceBelowIsNotSufficient&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='e2fky8r-informationRequestedPleaseDescribeTheRecordsYouAreRequestingBeAsSpecificAsPossibleAsThisWillAssistTheRequestProcessAttachASeparateSheetIfTheSpaceBelowIsNotSufficient']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e2fky8r']/div/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
   </webElementXpaths>
</WebElementEntity>
