<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Corporation_datasoleProprietorsNameIf_7df650</name>
   <tag></tag>
   <elementGuidId>a8f837ba-99a7-40b6-97b6-0b7f3944d25d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eunu6rj-soleProprietorsNameIfYouPlanToOperateABusinessOnYourOwnEitherUnderABusinessNameOrYourOwnName</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@class = 'form-control' and @type = 'text' and @name = 'data[soleProprietorsNameIfYouPlanToOperateABusinessOnYourOwnEitherUnderABusinessNameOrYourOwnName]']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='eunu6rj-soleProprietorsNameIfYouPlanToOperateABusinessOnYourOwnEitherUnderABusinessNameOrYourOwnName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eunu6rj-soleProprietorsNameIfYouPlanToOperateABusinessOnYourOwnEitherUnderABusinessNameOrYourOwnName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[soleProprietorsNameIfYouPlanToOperateABusinessOnYourOwnEitherUnderABusinessNameOrYourOwnName]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eunu6rj-soleProprietorsNameIfYouPlanToOperateABusinessOnYourOwnEitherUnderABusinessNameOrYourOwnName&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eunu6rj-soleProprietorsNameIfYouPlanToOperateABusinessOnYourOwnEitherUnderABusinessNameOrYourOwnName']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eunu6rj']/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div[2]/div/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
