name: Build and Push Docker Images

on:
  push:
    branches:
      - develop

defaults:
  run:
    shell: bash
    working-directory: ./forms-flow-documents

jobs:
  build-and-push:
    name: Build and Push Multi-Architecture Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: alanraju007
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: ./forms-flow-documents
          file: forms-flow-documents/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: alanraju007/forms-flow-documents-api:v7.0.0
          outputs: type=image
          build-args: |
            TARGETPLATFORM={{.TargetPlatform}}
          metadata: |
            variant={{.Variant}}
          files: |
            linux/amd64=Dockerfile=./forms-flow-documents/Dockerfile
            linux/arm64=Dockerfile=./forms-flow-documents/Dockerfile-ARM64

      - name: Verify Image in Registry
        run: |
          echo "Image pushed successfully!"
          docker run --rm alanraju007/forms-flow-documents-api:v7.0.0 --version
