name: Build and Push Docker Images for Documents-api

on:
  workflow_dispatch:
  push:
    branches: [ master, develop, release/* ]
    paths:
      - "forms-flow-documents/**"
      - "VERSION"

jobs:
  build-and-push:
    name: Build and Push Multi-Architecture Image
    #if: github.repository == 'AOT-Technologies/forms-flow-ai'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set version
        if: ${{ github.ref != 'refs/heads/master' }}
        working-directory: .
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      
      - name: Set version
        if: ${{ github.ref == 'refs/heads/master' }}
        working-directory: .
        run: |
          VER=$(cat VERSION)
          VER=${VER/-alpha/''}
          echo "VERSION=$VER" >> $GITHUB_ENV
      
      - run: echo ${{ env.VERSION }}

      #- name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.image }}
          tags: ${{ env.VERSION }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          # registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Push Multi-Arch Image
        run: |
          docker buildx create --name mybuilder --use
          cd ./forms-flow-documents
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file Dockerfile \
            --file Dockerfile-ARM64 \
            --tag alanraju007/forms-flow-documents-api:v1.0.0 \
            --push .