name: Push Forms flow forms to registry

on:
  push:
    branches: [ multi-tenancy-gha, develop, multi-tenancy ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
