name: Push Forms flow Web to registry

on:
  workflow_dispatch:
  push:
    branches: [ master, develop ]
    paths:
      - "forms-flow-web/**"

defaults:
  run:
    shell: bash
    working-directory: ./forms-flow-web

jobs:
  build-and-push-image-to-dockerhub:
    if: github.event_name == 'push' && github.repository == 'AOT-Technologies/forms-flow-ai'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: formsflow/forms-flow-web
            context: forms-flow-web
            dockerfile: Dockerfile
            name: forms-flow-web
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Set version
        working-directory: .
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      
      - run: echo ${{ env.VERSION }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.image }}
          tags: ${{ env.VERSION }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          # registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: forms-flow-web
          # builder: ${{ steps.buildx.outputs.name }}
          push: true
#           file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache-new
      # - name: Move cache
      #  run: |
      #    rm -rf /tmp/.buildx-cache
      #    mv /tmp/.buildx-cache-new /tmp/.buildx-cache
